/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness probe (DB, memory) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pending approvals assigned to the current user roles */
        get: operations["ApprovalController_findPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/approvals/{id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a pending workflow step */
        post: operations["ApprovalController_process"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/asset-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List asset units (paginated, searchable, lendable-only) */
        get: operations["AssetUnitController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/asset-units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete an asset unit */
        delete: operations["AssetUnitController_remove"];
        options?: never;
        head?: never;
        /** Update an asset unit (condition/status/location/custodian/etc.) */
        patch: operations["AssetUnitController_update"];
        trace?: never;
    };
    "/inventory/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all inventory assets (paginated, filterable) */
        get: operations["AssetController_findAll"];
        put?: never;
        /** Create a new asset (parent) with N numbered units (quantity) */
        post: operations["AssetController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset by ID */
        get: operations["AssetController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete an asset */
        delete: operations["AssetController_remove"];
        options?: never;
        head?: never;
        /** Update an existing asset */
        patch: operations["AssetController_update"];
        trace?: never;
    };
    "/inventory/assets/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add more physical units to an existing asset */
        post: operations["AssetController_addUnits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category list */
        get: operations["CategoryController_getCategories"];
        put?: never;
        /** Create category item */
        post: operations["CategoryController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete category item */
        delete: operations["CategoryController_deleteCategory"];
        options?: never;
        head?: never;
        /** Update category item */
        patch: operations["CategoryController_updateCategory"];
        trace?: never;
    };
    "/inventory/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get condition list */
        get: operations["ConditionController_getConditions"];
        put?: never;
        /** Create condition item */
        post: operations["ConditionController_createCondition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/conditions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete condition item */
        delete: operations["ConditionController_deleteCondition"];
        options?: never;
        head?: never;
        /** Update condition item */
        patch: operations["ConditionController_updateCondition"];
        trace?: never;
    };
    "/inventory/funding-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get funding source list */
        get: operations["FundingSourceController_getFundingSources"];
        put?: never;
        /** Create funding source item */
        post: operations["FundingSourceController_createFundingSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/funding-sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete funding source item */
        delete: operations["FundingSourceController_deleteFundingSource"];
        options?: never;
        head?: never;
        /** Update funding source item */
        patch: operations["FundingSourceController_updateFundingSource"];
        trace?: never;
    };
    "/inventory/histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all asset circulation history logs */
        get: operations["HistoryController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all loan transactions */
        get: operations["LoanController_findAll"];
        put?: never;
        /** Request a new loan */
        post: operations["LoanController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/loans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get loan transaction by ID */
        get: operations["LoanController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/loans/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return borrowed assets */
        post: operations["LoanController_returnLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get location list */
        get: operations["LocationController_getLocations"];
        put?: never;
        /** Create location item */
        post: operations["LocationController_createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete location item */
        delete: operations["LocationController_deleteLocation"];
        options?: never;
        head?: never;
        /** Update location item */
        patch: operations["LocationController_updateLocation"];
        trace?: never;
    };
    "/inventory/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get metadata for inventory dropdowns */
        get: operations["MetadataController_getMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status list */
        get: operations["StatusController_getStatuses"];
        put?: never;
        /** Create status item */
        post: operations["StatusController_createStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/statuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete status item */
        delete: operations["StatusController_deleteStatus"];
        options?: never;
        head?: never;
        /** Update status item */
        patch: operations["StatusController_updateStatus"];
        trace?: never;
    };
    "/inventory/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all workflow templates */
        get: operations["WorkflowController_findAll"];
        put?: never;
        /** Create a new workflow template */
        post: operations["WorkflowController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workflow template by ID */
        get: operations["WorkflowController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/workflows/role-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which roles approve steps of active workflows, for the role screen */
        get: operations["WorkflowController_roleUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApprovalProcessResultResponseConsequenceDto: {
            error?: string;
            /** @enum {string} */
            status: "NOT_REQUIRED" | "PENDING" | "COMPLETED" | "FAILED";
            /** @enum {string} */
            type: "NONE" | "FINAL_APPROVAL" | "REJECTION";
        };
        ApprovalProcessResultResponseDto: {
            /** @enum {string} */
            action: "REJECT" | "APPROVE_STEP" | "APPROVE_FINAL";
            consequence: components["schemas"]["ApprovalProcessResultResponseConsequenceDto"];
            log: components["schemas"]["ApprovalProcessResultResponseLogDto"];
            nextStepSequence?: number;
            retryable: boolean;
            success: boolean;
        };
        ApprovalProcessResultResponseLogDto: {
            actionId: string;
            approverId: string;
            consequenceError: string | null;
            /** @enum {string} */
            consequenceStatus: "NOT_REQUIRED" | "PENDING" | "COMPLETED" | "FAILED";
            /** @enum {string} */
            consequenceType: "NONE" | "FINAL_APPROVAL" | "REJECTION";
            /** Format: date-time */
            consequenceUpdatedAt: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            instanceId: string;
            note?: string | null;
            stepSequence: number;
        };
        ApprovalWorkflowResponseDto: {
            /** Format: date-time */
            createdAt: string;
            description?: string | null;
            id: string;
            isActive: boolean;
            name: string;
            steps?: components["schemas"]["ApprovalWorkflowResponseStepsDto"][];
            targetEntity: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ApprovalWorkflowResponseStepsDto: {
            approverRoleCode: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isMandatory: boolean;
            stepSequence: number;
            workflowId: string;
        };
        ApproveActionDto: {
            /**
             * @description Action to perform: APPROVE or REJECT
             * @enum {string}
             */
            action: "APPROVE" | "REJECT";
            /** @description Forward this loan to the next approver instead of finishing here. Only meaningful when the next step is optional — a mandatory one is always taken, and this cannot waive it. Ignored on a rejection. */
            forwardToNextApprover?: boolean;
            /** @description Optional rejection or approval note */
            note?: string;
        };
        CreateAssetDto: {
            /** @description Custom asset number */
            assetNumber?: string;
            /** @description Barcode identifier */
            barcode?: string;
            /** @description Brand name */
            brand?: string;
            /**
             * Format: uuid
             * @description Category UUID
             */
            categoryId: string;
            /**
             * Format: uuid
             * @description Condition UUID
             */
            conditionId: string;
            /**
             * Format: uuid
             * @description Funding Source UUID
             */
            fundingSourceId?: string;
            /**
             * Format: uuid
             * @description Location UUID
             */
            locationId: string;
            /** @description Model or Type */
            model?: string;
            /** @description Asset name */
            name: string;
            /** @description Extra notes */
            notes?: string;
            /** @description Purchase Date */
            purchaseDate: string;
            /** @description Purchase Price */
            purchasePrice: number;
            /**
             * @description Number of physical units to create (each gets its own number)
             * @default 1
             */
            quantity: number;
            /**
             * Format: uuid
             * @description Status UUID
             */
            statusId: string;
            /** @description Useful life in months */
            usefulLifeMonths?: number;
        };
        CreateCategoryDto: {
            /** @example CAT-001 */
            code: string;
            /** @example 10 */
            depreciationRatePercent: number;
            /** @example Elektronik */
            name: string;
        };
        CreateConditionDto: {
            /** @example COND-GOOD */
            code: string;
            /** @example true */
            isUsable?: boolean;
            /** @example Baik */
            name: string;
        };
        CreateFundingSourceDto: {
            /** @example FUND-GOV */
            code: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example APBD */
            name: string;
        };
        CreateLoanDto: {
            /** @description Expected date of returning the assets */
            expectedReturnDate: string;
            /** @description Purpose of borrowing */
            purpose: string;
            /** @description IDs of the asset units to borrow */
            unitIds: string[];
        };
        CreateLocationDto: {
            /** @example Gedung Utama */
            building?: string;
            /** @example LOC-A */
            code: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example Gedung Rektorat */
            name: string;
            /** @example Rak B */
            rack?: string;
            /** @example Ruang 301 */
            room?: string;
        };
        CreateStatusDto: {
            /** @example true */
            allowTransactions?: boolean;
            /** @example STATUS-ACTIVE */
            code: string;
            /** @example Aktif */
            name: string;
            /**
             * @description Protected role of this status in the loan lifecycle (null = custom, no special role).
             * @enum {string|null}
             */
            systemKey?: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        CreateUnitsDto: {
            /**
             * Format: uuid
             * @description Condition UUID (default unit baru)
             */
            conditionId: string;
            /**
             * Format: uuid
             * @description Location UUID (default unit baru)
             */
            locationId: string;
            /**
             * @description Jumlah unit tambahan
             * @default 1
             */
            quantity: number;
            /**
             * Format: uuid
             * @description Status UUID (default unit baru)
             */
            statusId: string;
        };
        CreateWorkflowDto: {
            description?: string;
            /** @description Name of the workflow */
            name: string;
            steps: components["schemas"]["CreateWorkflowStepDto"][];
            /** @description Target entity class name */
            targetEntity: string;
        };
        CreateWorkflowStepDto: {
            /** @description Role code authorized to approve this step (e.g. ADMIN, PRINCIPAL) */
            approverRoleCode: string;
            /**
             * @description False leaves this step to the previous approver, who decides per request whether it is also taken. A mandatory step is always taken.
             * @default true
             */
            isMandatory: boolean;
            /** @description Sequence number of the step (1-indexed) */
            stepSequence: number;
        };
        InventoryAssetListItemResponseCategoryDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetListItemResponseCountDto: {
            units?: number;
        };
        InventoryAssetListItemResponseDto: {
            _count?: components["schemas"]["InventoryAssetListItemResponseCountDto"];
            assetNumber: string;
            brand?: string | null;
            category?: components["schemas"]["InventoryAssetListItemResponseCategoryDto"];
            categoryId: string;
            /** Format: date-time */
            createdAt?: string;
            fundingSource?: components["schemas"]["InventoryAssetListItemResponseFundingSourceDto"] | null;
            fundingSourceId?: string | null;
            id: string;
            imageUrl?: string | null;
            model?: string | null;
            name: string;
            notes?: string | null;
            /** Format: date-time */
            purchaseDate: string;
            purchasePrice: number;
            units?: components["schemas"]["InventoryAssetListItemResponseUnitsDto"][];
            /** Format: date-time */
            updatedAt?: string;
            usefulLifeMonths?: number | null;
            version?: number;
        };
        InventoryAssetListItemResponseFundingSourceDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetListItemResponseUnitsAssetCategoryDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetListItemResponseUnitsAssetDto: {
            assetNumber: string;
            category: components["schemas"]["InventoryAssetListItemResponseUnitsAssetCategoryDto"] | null;
            id: string;
            name: string;
        };
        InventoryAssetListItemResponseUnitsConditionDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetListItemResponseUnitsDto: {
            asset?: components["schemas"]["InventoryAssetListItemResponseUnitsAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryAssetListItemResponseUnitsConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt?: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryAssetListItemResponseUnitsLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryAssetListItemResponseUnitsStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt?: string;
            version?: number;
        };
        InventoryAssetListItemResponseUnitsLocationDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetListItemResponseUnitsStatusDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetListResponseDto: {
            data: components["schemas"]["InventoryAssetListItemResponseDto"][];
            limit: number;
            page: number;
            total: number;
        };
        InventoryAssetResponseCategoryDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetResponseCountDto: {
            units?: number;
        };
        InventoryAssetResponseDto: {
            _count?: components["schemas"]["InventoryAssetResponseCountDto"];
            assetNumber: string;
            brand?: string | null;
            category?: components["schemas"]["InventoryAssetResponseCategoryDto"];
            categoryId: string;
            /** Format: date-time */
            createdAt?: string;
            fundingSource?: components["schemas"]["InventoryAssetResponseFundingSourceDto"] | null;
            fundingSourceId?: string | null;
            id: string;
            imageUrl?: string | null;
            model?: string | null;
            name: string;
            notes?: string | null;
            /** Format: date-time */
            purchaseDate: string;
            purchasePrice: number;
            units?: components["schemas"]["InventoryAssetResponseUnitsDto"][];
            /** Format: date-time */
            updatedAt?: string;
            usefulLifeMonths?: number | null;
            version?: number;
        };
        InventoryAssetResponseFundingSourceDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetResponseUnitsAssetCategoryDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetResponseUnitsAssetDto: {
            assetNumber: string;
            category: components["schemas"]["InventoryAssetResponseUnitsAssetCategoryDto"] | null;
            id: string;
            name: string;
        };
        InventoryAssetResponseUnitsConditionDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetResponseUnitsDto: {
            asset?: components["schemas"]["InventoryAssetResponseUnitsAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryAssetResponseUnitsConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt?: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryAssetResponseUnitsLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryAssetResponseUnitsStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt?: string;
            version?: number;
        };
        InventoryAssetResponseUnitsLocationDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetResponseUnitsStatusDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitListItemResponseAssetCategoryDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitListItemResponseAssetDto: {
            assetNumber: string;
            category: components["schemas"]["InventoryAssetUnitListItemResponseAssetCategoryDto"] | null;
            id: string;
            name: string;
        };
        InventoryAssetUnitListItemResponseConditionDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitListItemResponseDto: {
            asset?: components["schemas"]["InventoryAssetUnitListItemResponseAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryAssetUnitListItemResponseConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt?: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryAssetUnitListItemResponseLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryAssetUnitListItemResponseStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt?: string;
            version?: number;
        };
        InventoryAssetUnitListItemResponseLocationDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitListItemResponseStatusDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitListResponseDto: {
            data: components["schemas"]["InventoryAssetUnitListItemResponseDto"][];
            limit: number;
            page: number;
            total: number;
        };
        InventoryAssetUnitResponseAssetCategoryDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitResponseAssetDto: {
            assetNumber: string;
            category: components["schemas"]["InventoryAssetUnitResponseAssetCategoryDto"] | null;
            id: string;
            name: string;
        };
        InventoryAssetUnitResponseConditionDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitResponseDto: {
            asset?: components["schemas"]["InventoryAssetUnitResponseAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryAssetUnitResponseConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt?: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryAssetUnitResponseLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryAssetUnitResponseStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt?: string;
            version?: number;
        };
        InventoryAssetUnitResponseLocationDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryAssetUnitResponseStatusDto: {
            code: string;
            id: string;
            name: string;
        };
        InventoryCategoryResponseDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            depreciationRatePercent: string;
            id: string;
            name: string;
            parentId: string | null;
        };
        InventoryConditionResponseDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isUsable: boolean;
            name: string;
        };
        InventoryFundingSourceResponseDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            id: string;
            name: string;
        };
        InventoryHistoryListResponseDto: {
            data: components["schemas"]["InventoryHistoryResponseDto"][];
            limit: number;
            page: number;
            total: number;
        };
        InventoryHistoryResponseDto: {
            /** Format: date-time */
            changedAt: string;
            changedById: string;
            id: string;
            newConditionId?: string | null;
            newCustodianId?: string | null;
            newLocationId?: string | null;
            newStatusId?: string | null;
            note?: string | null;
            operationKey?: string | null;
            previousConditionId?: string | null;
            previousCustodianId?: string | null;
            previousLocationId?: string | null;
            previousStatusId?: string | null;
            transactionType?: components["schemas"]["InventoryHistoryResponseTransactionTypeDto"];
            transactionTypeId: string;
            unit?: components["schemas"]["InventoryHistoryResponseUnitDto"];
            unitId: string;
        };
        InventoryHistoryResponseTransactionTypeDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            description?: string | null;
            direction: string;
            id: string;
            name: string;
        };
        InventoryHistoryResponseUnitAssetDto: {
            assetNumber: string;
            brand?: string | null;
            categoryId: string;
            /** Format: date-time */
            createdAt: string;
            fundingSourceId?: string | null;
            id: string;
            imageUrl?: string | null;
            model?: string | null;
            name: string;
            notes?: string | null;
            /** Format: date-time */
            purchaseDate: string;
            purchasePrice: number;
            /** Format: date-time */
            updatedAt: string;
            usefulLifeMonths: number;
            version: number;
        };
        InventoryHistoryResponseUnitConditionDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isUsable: boolean;
            name: string;
        };
        InventoryHistoryResponseUnitDto: {
            asset?: components["schemas"]["InventoryHistoryResponseUnitAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryHistoryResponseUnitConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryHistoryResponseUnitLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryHistoryResponseUnitStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        InventoryHistoryResponseUnitLocationDto: {
            building?: string | null;
            code: string;
            /** Format: date-time */
            createdAt: string;
            description?: string | null;
            id: string;
            name: string;
            rack?: string | null;
            room?: string | null;
        };
        InventoryHistoryResponseUnitStatusDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            systemKey?: string | null;
        };
        InventoryLoanListItemResponseDto: {
            /** Format: date-time */
            actualReturnDate?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expectedReturnDate: string;
            id: string;
            items?: components["schemas"]["InventoryLoanListItemResponseItemsDto"][];
            loanNumber: string;
            purpose: string;
            requester?: components["schemas"]["InventoryLoanListItemResponseRequesterDto"] | null;
            requesterId: string;
            status?: components["schemas"]["InventoryLoanListItemResponseStatusDto"] | null;
            statusId: string;
            /** Format: date-time */
            updatedAt?: string;
            workflowInstanceId?: string | null;
        };
        InventoryLoanListItemResponseItemsDto: {
            id: string;
            loanId: string;
            note?: string | null;
            notes?: string | null;
            returnedConditionId?: string | null;
            unit?: components["schemas"]["InventoryLoanListItemResponseItemsUnitDto"];
            unitId: string;
        };
        InventoryLoanListItemResponseItemsUnitAssetDto: {
            assetNumber: string;
            brand?: string | null;
            categoryId: string;
            /** Format: date-time */
            createdAt: string;
            fundingSourceId?: string | null;
            id: string;
            imageUrl?: string | null;
            model?: string | null;
            name: string;
            notes?: string | null;
            /** Format: date-time */
            purchaseDate: string;
            purchasePrice: number;
            /** Format: date-time */
            updatedAt: string;
            usefulLifeMonths: number;
            version: number;
        };
        InventoryLoanListItemResponseItemsUnitConditionDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isUsable: boolean;
            name: string;
        };
        InventoryLoanListItemResponseItemsUnitDto: {
            asset?: components["schemas"]["InventoryLoanListItemResponseItemsUnitAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryLoanListItemResponseItemsUnitConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryLoanListItemResponseItemsUnitLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryLoanListItemResponseItemsUnitStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        InventoryLoanListItemResponseItemsUnitLocationDto: {
            building?: string | null;
            code: string;
            /** Format: date-time */
            createdAt: string;
            description?: string | null;
            id: string;
            name: string;
            rack?: string | null;
            room?: string | null;
        };
        InventoryLoanListItemResponseItemsUnitStatusDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            systemKey?: string | null;
        };
        InventoryLoanListItemResponseRequesterDto: {
            id: string;
            identifier: string;
        };
        InventoryLoanListItemResponseStatusDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt?: string;
            id: string;
            name: string;
            systemKey?: string | null;
        };
        InventoryLoanListResponseDto: {
            data: components["schemas"]["InventoryLoanListItemResponseDto"][];
            limit: number;
            page: number;
            total: number;
        };
        InventoryLoanResponseDto: {
            /** Format: date-time */
            actualReturnDate?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expectedReturnDate: string;
            id: string;
            items?: components["schemas"]["InventoryLoanResponseItemsDto"][];
            loanNumber: string;
            purpose: string;
            requester?: components["schemas"]["InventoryLoanResponseRequesterDto"] | null;
            requesterId: string;
            status?: components["schemas"]["InventoryLoanResponseStatusDto"] | null;
            statusId: string;
            /** Format: date-time */
            updatedAt?: string;
            workflowInstanceId?: string | null;
        };
        InventoryLoanResponseItemsDto: {
            id: string;
            loanId: string;
            note?: string | null;
            notes?: string | null;
            returnedConditionId?: string | null;
            unit?: components["schemas"]["InventoryLoanResponseItemsUnitDto"];
            unitId: string;
        };
        InventoryLoanResponseItemsUnitAssetDto: {
            assetNumber: string;
            brand?: string | null;
            categoryId: string;
            /** Format: date-time */
            createdAt: string;
            fundingSourceId?: string | null;
            id: string;
            imageUrl?: string | null;
            model?: string | null;
            name: string;
            notes?: string | null;
            /** Format: date-time */
            purchaseDate: string;
            purchasePrice: number;
            /** Format: date-time */
            updatedAt: string;
            usefulLifeMonths: number;
            version: number;
        };
        InventoryLoanResponseItemsUnitConditionDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isUsable: boolean;
            name: string;
        };
        InventoryLoanResponseItemsUnitDto: {
            asset?: components["schemas"]["InventoryLoanResponseItemsUnitAssetDto"];
            assetId: string;
            barcode?: string | null;
            condition?: components["schemas"]["InventoryLoanResponseItemsUnitConditionDto"];
            conditionId: string;
            /** Format: date-time */
            createdAt: string;
            currentBookValue: number;
            custodianId?: string | null;
            id: string;
            location?: components["schemas"]["InventoryLoanResponseItemsUnitLocationDto"];
            locationId: string;
            notes?: string | null;
            status?: components["schemas"]["InventoryLoanResponseItemsUnitStatusDto"];
            statusId: string;
            unitNumber: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        InventoryLoanResponseItemsUnitLocationDto: {
            building?: string | null;
            code: string;
            /** Format: date-time */
            createdAt: string;
            description?: string | null;
            id: string;
            name: string;
            rack?: string | null;
            room?: string | null;
        };
        InventoryLoanResponseItemsUnitStatusDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            systemKey?: string | null;
        };
        InventoryLoanResponseRequesterDto: {
            id: string;
            identifier: string;
        };
        InventoryLoanResponseStatusDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt?: string;
            id: string;
            name: string;
            systemKey?: string | null;
        };
        InventoryLocationResponseDto: {
            building: string | null;
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            id: string;
            name: string;
            rack: string | null;
            room: string | null;
        };
        InventoryMetadataResponseCategoriesDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            depreciationRatePercent: string;
            id: string;
            name: string;
            parentId: string | null;
        };
        InventoryMetadataResponseConditionsDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isUsable: boolean;
            name: string;
        };
        InventoryMetadataResponseDto: {
            categories: components["schemas"]["InventoryMetadataResponseCategoriesDto"][];
            conditions: components["schemas"]["InventoryMetadataResponseConditionsDto"][];
            fundingSources: components["schemas"]["InventoryMetadataResponseFundingSourcesDto"][];
            locations: components["schemas"]["InventoryMetadataResponseLocationsDto"][];
            statuses: components["schemas"]["InventoryMetadataResponseStatusesDto"][];
        };
        InventoryMetadataResponseFundingSourcesDto: {
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            id: string;
            name: string;
        };
        InventoryMetadataResponseLocationsDto: {
            building: string | null;
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            id: string;
            name: string;
            rack: string | null;
            room: string | null;
        };
        InventoryMetadataResponseStatusesDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            /** @enum {string|null} */
            systemKey: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        InventoryStatusResponseDto: {
            allowTransactions: boolean;
            code: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            /** @enum {string|null} */
            systemKey: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        PendingApprovalResponseDetailsDto: {
            /** Format: date-time */
            expectedReturnDate?: string | null;
            id: string;
            items: components["schemas"]["PendingApprovalResponseDetailsItemsDto"][];
            loanNumber: string;
            purpose?: string | null;
        };
        PendingApprovalResponseDetailsItemsDto: {
            id: string;
            unit?: components["schemas"]["PendingApprovalResponseDetailsItemsUnitDto"] | null;
            unitId: string;
        };
        PendingApprovalResponseDetailsItemsUnitAssetDto: {
            id: string;
            name: string;
        };
        PendingApprovalResponseDetailsItemsUnitDto: {
            asset?: components["schemas"]["PendingApprovalResponseDetailsItemsUnitAssetDto"] | null;
            id: string;
            unitNumber: string;
        };
        PendingApprovalResponseDto: {
            /** Format: date-time */
            createdAt: string;
            currentStepSequence: number;
            details: components["schemas"]["PendingApprovalResponseDetailsDto"] | null;
            id: string;
            logs?: components["schemas"]["PendingApprovalResponseLogsDto"][];
            referenceId: string;
            statusId: string;
            /** Format: date-time */
            updatedAt: string;
            workflow?: components["schemas"]["PendingApprovalResponseWorkflowDto"] | null;
            workflowId: string;
        };
        PendingApprovalResponseLogsDto: {
            actionId: string;
            approverId: string;
            consequenceError: string | null;
            /** @enum {string} */
            consequenceStatus: "NOT_REQUIRED" | "PENDING" | "COMPLETED" | "FAILED";
            /** @enum {string} */
            consequenceType: "NONE" | "FINAL_APPROVAL" | "REJECTION";
            /** Format: date-time */
            consequenceUpdatedAt: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            instanceId: string;
            note?: string | null;
            stepSequence: number;
        };
        PendingApprovalResponseWorkflowDto: {
            /** Format: date-time */
            createdAt: string;
            description?: string | null;
            id: string;
            isActive: boolean;
            name: string;
            steps?: components["schemas"]["PendingApprovalResponseWorkflowStepsDto"][];
            targetEntity: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PendingApprovalResponseWorkflowStepsDto: {
            approverRoleCode: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            isMandatory: boolean;
            stepSequence: number;
            workflowId: string;
        };
        ReturnLoanDto: {
            items: components["schemas"]["ReturnLoanItemDto"][];
        };
        ReturnLoanItemDto: {
            /** @description Notes on returning the asset */
            notes?: string;
            /**
             * Format: uuid
             * @description Condition ID of the asset when returned
             */
            returnedConditionId: string;
            /**
             * Format: uuid
             * @description Asset unit ID being returned
             */
            unitId: string;
        };
        RoleUsageResponseDto: {
            /** @example PRINCIPAL */
            roleCode: string;
            /** @description Active approval steps this role approves */
            steps: number;
            /** @description Active workflows with such a step */
            workflows: string[];
        };
        UpdateAssetDto: {
            /** @description Batch/asset number */
            assetNumber?: string;
            /** @description Brand name */
            brand?: string;
            /**
             * Format: uuid
             * @description Category UUID
             */
            categoryId?: string;
            /**
             * Format: uuid
             * @description Funding Source UUID
             */
            fundingSourceId?: string;
            /** @description Model or Type */
            model?: string;
            /** @description Asset name */
            name?: string;
            /** @description Extra notes */
            notes?: string;
            /** @description Purchase Date */
            purchaseDate?: string;
            /** @description Purchase Price (per unit) */
            purchasePrice?: number;
            /** @description Useful life in months */
            usefulLifeMonths?: number;
        };
        UpdateCategoryDto: {
            /** @example CAT-001 */
            code?: string;
            /** @example 10 */
            depreciationRatePercent?: number;
            /** @example Elektronik */
            name?: string;
        };
        UpdateConditionDto: {
            /** @example COND-GOOD */
            code?: string;
            /** @example true */
            isUsable?: boolean;
            /** @example Baik */
            name?: string;
        };
        UpdateFundingSourceDto: {
            /** @example FUND-GOV */
            code?: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example APBD */
            name?: string;
        };
        UpdateLocationDto: {
            /** @example Gedung Utama */
            building?: string;
            /** @example LOC-A */
            code?: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example Gedung Rektorat */
            name?: string;
            /** @example Rak B */
            rack?: string;
            /** @example Ruang 301 */
            room?: string;
        };
        UpdateStatusDto: {
            /** @example true */
            allowTransactions?: boolean;
            /** @example STATUS-ACTIVE */
            code?: string;
            /** @example Aktif */
            name?: string;
            /**
             * @description Protected role of this status in the loan lifecycle (null = custom, no special role).
             * @enum {string|null}
             */
            systemKey?: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        UpdateUnitDto: {
            /** @description Barcode / QR code */
            barcode?: string;
            /**
             * Format: uuid
             * @description Condition UUID
             */
            conditionId?: string;
            /**
             * Format: uuid
             * @description Custodian user UUID
             */
            custodianId?: string;
            /**
             * Format: uuid
             * @description Location UUID
             */
            locationId?: string;
            /** @description Notes */
            notes?: string;
            /**
             * Format: uuid
             * @description Status UUID
             */
            statusId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            details?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            };
                            /** @example {} */
                            error?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            info?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status?: "ok" | "degraded";
                        };
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                    };
                };
            };
        };
    };
    ApprovalController_findPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PendingApprovalResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ApprovalController_process: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveActionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApprovalProcessResultResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetUnitController_findAll: {
        parameters: {
            query?: {
                /** @description Only units whose status permits transactions — what a loan form needs. Units already reserved by a pending loan, or out on an approved one, hold a status that forbids transactions and are excluded by the same rule. */
                lendable?: boolean;
                limit?: number;
                page?: number;
                /** @description Matches unit number or asset name. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetUnitListItemResponseDto"][];
                        /** @example Success */
                        message?: string;
                        meta?: {
                            limit?: number;
                            page?: number;
                            total?: number;
                        };
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetUnitController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetUnitController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetUnitResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_findAll: {
        parameters: {
            query?: {
                categoryId?: string;
                conditionId?: string;
                fundingSourceId?: string;
                keyword?: string;
                limit?: number;
                locationId?: string;
                page?: number;
                statusId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetListItemResponseDto"][];
                        /** @example Success */
                        message?: string;
                        meta?: {
                            limit?: number;
                            page?: number;
                            total?: number;
                        };
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_addUnits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryAssetUnitResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CategoryController_getCategories: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryCategoryResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CategoryController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CategoryController_deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoryController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ConditionController_getConditions: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryConditionResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ConditionController_createCondition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConditionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryConditionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ConditionController_deleteCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConditionController_updateCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConditionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryConditionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    FundingSourceController_getFundingSources: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryFundingSourceResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    FundingSourceController_createFundingSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFundingSourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryFundingSourceResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    FundingSourceController_deleteFundingSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FundingSourceController_updateFundingSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFundingSourceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryFundingSourceResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    HistoryController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                unitId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryHistoryResponseDto"][];
                        /** @example Success */
                        message?: string;
                        meta?: {
                            limit?: number;
                            page?: number;
                            total?: number;
                        };
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LoanController_findAll: {
        parameters: {
            query?: {
                keyword?: string;
                limit?: number;
                page?: number;
                requesterId?: string;
                statusId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLoanListItemResponseDto"][];
                        /** @example Success */
                        message?: string;
                        meta?: {
                            limit?: number;
                            page?: number;
                            total?: number;
                        };
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LoanController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoanDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLoanResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LoanController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLoanResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LoanController_returnLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnLoanDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLoanResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LocationController_getLocations: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLocationResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LocationController_createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLocationResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LocationController_deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationController_updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLocationResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    MetadataController_getMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryMetadataResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    StatusController_getStatuses: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryStatusResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    StatusController_createStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatusDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryStatusResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    StatusController_deleteStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatusController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryStatusResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApprovalWorkflowResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApprovalWorkflowResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApprovalWorkflowResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_roleUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["RoleUsageResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
}
