export enum AdmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  REVISION_NEEDED = 'REVISION_NEEDED',
  VERIFIED = 'VERIFIED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  ENROLLED = 'ENROLLED',
}
