export enum InventoryStatusKey {
  AVAILABLE = 'AVAILABLE',
  LOANED = 'LOANED',
  LOAN_PENDING = 'LOAN_PENDING',
  LOAN_APPROVED = 'LOAN_APPROVED',
  LOAN_REJECTED = 'LOAN_REJECTED',
  LOAN_RETURNED = 'LOAN_RETURNED',
}
