import { OccupationUsage } from './simple-list/occupation-usage.js'
import type { SimpleListDefinition } from './simple-list/simple-list.types.js'

export const SIMPLE_LISTS: SimpleListDefinition[] = [
  {
    model: 'occupation',
    path: 'occupations',
    permission: 'occupations',
    className: 'Occupation',
    label: 'Occupation',
    tag: 'Occupations',
    usage: OccupationUsage,
  },
  {
    model: 'education',
    path: 'educations',
    permission: 'educations',
    className: 'Education',
    label: 'Education',
    tag: 'Educations',
  },
  {
    model: 'incomeRange',
    path: 'income-ranges',
    permission: 'income-ranges',
    className: 'IncomeRange',
    label: 'Income range',
    tag: 'Income ranges',
  },
  {
    model: 'financingSource',
    path: 'financing-sources',
    permission: 'financing-sources',
    className: 'FinancingSource',
    label: 'Financing source',
    tag: 'Financing sources',
  },
  {
    model: 'disabilityType',
    path: 'disability-types',
    permission: 'disability-types',
    className: 'DisabilityType',
    label: 'Disability type',
    tag: 'Disability types',
  },
  {
    model: 'specialNeed',
    path: 'special-needs',
    permission: 'special-needs',
    className: 'SpecialNeed',
    label: 'Special need',
    tag: 'Special needs',
  },
  {
    model: 'studentResidence',
    path: 'student-residences',
    permission: 'student-residences',
    className: 'StudentResidence',
    label: 'Student residence',
    tag: 'Student residences',
  },
  {
    model: 'parentResidence',
    path: 'parent-residences',
    permission: 'parent-residences',
    className: 'ParentResidence',
    label: 'Parent residence',
    tag: 'Parent residences',
  },
  {
    model: 'transportation',
    path: 'transportations',
    permission: 'transportations',
    className: 'Transportation',
    label: 'Transportation',
    tag: 'Transportations',
  },
  {
    model: 'travelDistance',
    path: 'travel-distances',
    permission: 'travel-distances',
    className: 'TravelDistance',
    label: 'Travel distance',
    tag: 'Travel distances',
  },
  {
    model: 'travelTime',
    path: 'travel-times',
    permission: 'travel-times',
    className: 'TravelTime',
    label: 'Travel time',
    tag: 'Travel times',
  },
  {
    model: 'parentLifeStatus',
    path: 'parent-life-statuses',
    permission: 'parent-life-statuses',
    className: 'ParentLifeStatus',
    label: 'Parent life status',
    tag: 'Parent life statuses',
  },
  {
    model: 'domicile',
    path: 'domiciles',
    permission: 'domiciles',
    className: 'Domicile',
    label: 'Domicile',
    tag: 'Domiciles',
  },
  {
    model: 'scholarshipCategory',
    path: 'scholarship-categories',
    permission: 'scholarship-categories',
    className: 'ScholarshipCategory',
    label: 'Scholarship category',
    tag: 'Scholarship categories',
  },
  {
    model: 'scholarshipProviderType',
    path: 'scholarship-provider-types',
    permission: 'scholarship-provider-types',
    className: 'ScholarshipProviderType',
    label: 'Scholarship provider type',
    tag: 'Scholarship provider types',
  },
  {
    model: 'competitionField',
    path: 'competition-fields',
    permission: 'competition-fields',
    className: 'CompetitionField',
    label: 'Competition field',
    tag: 'Competition fields',
  },
  {
    model: 'competitionLevel',
    path: 'competition-levels',
    permission: 'competition-levels',
    className: 'CompetitionLevel',
    label: 'Competition level',
    tag: 'Competition levels',
  },
]
