/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness probe (DB, memory) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pending approvals assigned to the current user roles */
        get: operations["ApprovalController_findPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/approvals/{id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a pending workflow step */
        post: operations["ApprovalController_process"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/asset-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List asset units (paginated, searchable, lendable-only) */
        get: operations["AssetUnitController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/asset-units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete an asset unit */
        delete: operations["AssetUnitController_remove"];
        options?: never;
        head?: never;
        /** Update an asset unit (condition/status/location/custodian/etc.) */
        patch: operations["AssetUnitController_update"];
        trace?: never;
    };
    "/inventory/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all inventory assets (paginated, filterable) */
        get: operations["AssetController_findAll"];
        put?: never;
        /** Create a new asset (parent) with N numbered units (quantity) */
        post: operations["AssetController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset by ID */
        get: operations["AssetController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete an asset */
        delete: operations["AssetController_remove"];
        options?: never;
        head?: never;
        /** Update an existing asset */
        patch: operations["AssetController_update"];
        trace?: never;
    };
    "/inventory/assets/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add more physical units to an existing asset */
        post: operations["AssetController_addUnits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category list */
        get: operations["CategoryController_getCategories"];
        put?: never;
        /** Create category item */
        post: operations["CategoryController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete category item */
        delete: operations["CategoryController_deleteCategory"];
        options?: never;
        head?: never;
        /** Update category item */
        patch: operations["CategoryController_updateCategory"];
        trace?: never;
    };
    "/inventory/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get condition list */
        get: operations["ConditionController_getConditions"];
        put?: never;
        /** Create condition item */
        post: operations["ConditionController_createCondition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/conditions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete condition item */
        delete: operations["ConditionController_deleteCondition"];
        options?: never;
        head?: never;
        /** Update condition item */
        patch: operations["ConditionController_updateCondition"];
        trace?: never;
    };
    "/inventory/funding-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get funding source list */
        get: operations["FundingSourceController_getFundingSources"];
        put?: never;
        /** Create funding source item */
        post: operations["FundingSourceController_createFundingSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/funding-sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete funding source item */
        delete: operations["FundingSourceController_deleteFundingSource"];
        options?: never;
        head?: never;
        /** Update funding source item */
        patch: operations["FundingSourceController_updateFundingSource"];
        trace?: never;
    };
    "/inventory/histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all asset circulation history logs */
        get: operations["HistoryController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all loan transactions */
        get: operations["LoanController_findAll"];
        put?: never;
        /** Request a new loan */
        post: operations["LoanController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/loans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get loan transaction by ID */
        get: operations["LoanController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/loans/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return borrowed assets */
        post: operations["LoanController_returnLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get location list */
        get: operations["LocationController_getLocations"];
        put?: never;
        /** Create location item */
        post: operations["LocationController_createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete location item */
        delete: operations["LocationController_deleteLocation"];
        options?: never;
        head?: never;
        /** Update location item */
        patch: operations["LocationController_updateLocation"];
        trace?: never;
    };
    "/inventory/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get metadata for inventory dropdowns */
        get: operations["MetadataController_getMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status list */
        get: operations["StatusController_getStatuses"];
        put?: never;
        /** Create status item */
        post: operations["StatusController_createStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/statuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete status item */
        delete: operations["StatusController_deleteStatus"];
        options?: never;
        head?: never;
        /** Update status item */
        patch: operations["StatusController_updateStatus"];
        trace?: never;
    };
    "/inventory/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all workflow templates */
        get: operations["WorkflowController_findAll"];
        put?: never;
        /** Create a new workflow template */
        post: operations["WorkflowController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workflow template by ID */
        get: operations["WorkflowController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApproveActionDto: {
            /**
             * @description Action to perform: APPROVE or REJECT
             * @enum {string}
             */
            action: "APPROVE" | "REJECT";
            /** @description Forward this loan to the next approver instead of finishing here. Only meaningful when the next step is optional — a mandatory one is always taken, and this cannot waive it. Ignored on a rejection. */
            forwardToNextApprover?: boolean;
            /** @description Optional rejection or approval note */
            note?: string;
        };
        CreateAssetDto: {
            /** @description Custom asset number */
            assetNumber?: string;
            /** @description Barcode identifier */
            barcode?: string;
            /** @description Brand name */
            brand?: string;
            /**
             * Format: uuid
             * @description Category UUID
             */
            categoryId: string;
            /**
             * Format: uuid
             * @description Condition UUID
             */
            conditionId: string;
            /**
             * Format: uuid
             * @description Funding Source UUID
             */
            fundingSourceId?: string;
            /**
             * Format: uuid
             * @description Location UUID
             */
            locationId: string;
            /** @description Model or Type */
            model?: string;
            /** @description Asset name */
            name: string;
            /** @description Extra notes */
            notes?: string;
            /** @description Purchase Date */
            purchaseDate: string;
            /** @description Purchase Price */
            purchasePrice: number;
            /**
             * @description Number of physical units to create (each gets its own number)
             * @default 1
             */
            quantity: number;
            /**
             * Format: uuid
             * @description Status UUID
             */
            statusId: string;
            /** @description Useful life in months */
            usefulLifeMonths?: number;
        };
        CreateCategoryDto: {
            /** @example CAT-001 */
            code: string;
            /** @example 10 */
            depreciationRatePercent: number;
            /** @example Elektronik */
            name: string;
        };
        CreateConditionDto: {
            /** @example COND-GOOD */
            code: string;
            /** @example true */
            isUsable?: boolean;
            /** @example Baik */
            name: string;
        };
        CreateFundingSourceDto: {
            /** @example FUND-GOV */
            code: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example APBD */
            name: string;
        };
        CreateLoanDto: {
            /** @description Expected date of returning the assets */
            expectedReturnDate: string;
            /** @description Purpose of borrowing */
            purpose: string;
            /** @description IDs of the asset units to borrow */
            unitIds: string[];
        };
        CreateLocationDto: {
            /** @example Gedung Utama */
            building?: string;
            /** @example LOC-A */
            code: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example Gedung Rektorat */
            name: string;
            /** @example Rak B */
            rack?: string;
            /** @example Ruang 301 */
            room?: string;
        };
        CreateStatusDto: {
            /** @example true */
            allowTransactions?: boolean;
            /** @example STATUS-ACTIVE */
            code: string;
            /** @example Aktif */
            name: string;
            /**
             * @description Protected role of this status in the loan lifecycle (null = custom, no special role).
             * @enum {string|null}
             */
            systemKey?: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        CreateUnitsDto: {
            /**
             * Format: uuid
             * @description Condition UUID (default unit baru)
             */
            conditionId: string;
            /**
             * Format: uuid
             * @description Location UUID (default unit baru)
             */
            locationId: string;
            /**
             * @description Jumlah unit tambahan
             * @default 1
             */
            quantity: number;
            /**
             * Format: uuid
             * @description Status UUID (default unit baru)
             */
            statusId: string;
        };
        CreateWorkflowDto: {
            description?: string;
            /** @description Name of the workflow */
            name: string;
            steps: components["schemas"]["CreateWorkflowStepDto"][];
            /** @description Target entity class name */
            targetEntity: string;
        };
        CreateWorkflowStepDto: {
            /** @description Role code authorized to approve this step (e.g. ADMIN, PRINCIPAL) */
            approverRoleCode: string;
            /**
             * @description False leaves this step to the previous approver, who decides per request whether it is also taken. A mandatory step is always taken.
             * @default true
             */
            isMandatory: boolean;
            /** @description Sequence number of the step (1-indexed) */
            stepSequence: number;
        };
        InventoryCategoryResponseDto: {
            /** @example ELK */
            code: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description A string, not a number: the column is `Decimal(5,2)`, and Prisma hands a Decimal back as its string form so no precision is lost on the way.
             * @example 12.50
             */
            depreciationRatePercent: string;
            /** Format: uuid */
            id: string;
            /** @example Elektronik */
            name: string;
            /**
             * Format: uuid
             * @description Categories nest; null at the top of a tree.
             */
            parentId: string | null;
        };
        InventoryConditionResponseDto: {
            /** @example BAIK */
            code: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /**
             * @description Whether an asset in this condition may still be lent out.
             * @example true
             */
            isUsable: boolean;
            /** @example Baik */
            name: string;
        };
        InventoryFundingSourceResponseDto: {
            /** @example BOS */
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            /** Format: uuid */
            id: string;
            /** @example Dana BOS */
            name: string;
        };
        InventoryLocationResponseDto: {
            /** @example Gedung A */
            building: string | null;
            /** @example LAB1 */
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            /** Format: uuid */
            id: string;
            /** @example Laboratorium 1 */
            name: string;
            /** @example Rak 3 */
            rack: string | null;
            /** @example R-08 */
            room: string | null;
        };
        InventoryMetadataResponseDto: {
            categories: components["schemas"]["InventoryCategoryResponseDto"][];
            conditions: components["schemas"]["InventoryConditionResponseDto"][];
            fundingSources: components["schemas"]["InventoryFundingSourceResponseDto"][];
            locations: components["schemas"]["InventoryLocationResponseDto"][];
            statuses: components["schemas"]["InventoryStatusResponseDto"][];
        };
        InventoryStatusResponseDto: {
            /**
             * @description Whether an asset in this status may be borrowed or returned.
             * @example true
             */
            allowTransactions: boolean;
            /** @example TERSEDIA */
            code: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** @example Tersedia */
            name: string;
            /**
             * @description Set only on the statuses the workflow reasons about, so renaming one in the interface cannot change what the code does with it.
             * @enum {string|null}
             */
            systemKey: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        ReturnLoanDto: {
            items: components["schemas"]["ReturnLoanItemDto"][];
        };
        ReturnLoanItemDto: {
            /** @description Notes on returning the asset */
            notes?: string;
            /**
             * Format: uuid
             * @description Condition ID of the asset when returned
             */
            returnedConditionId: string;
            /**
             * Format: uuid
             * @description Asset unit ID being returned
             */
            unitId: string;
        };
        UpdateAssetDto: {
            /** @description Batch/asset number */
            assetNumber?: string;
            /** @description Brand name */
            brand?: string;
            /**
             * Format: uuid
             * @description Category UUID
             */
            categoryId?: string;
            /**
             * Format: uuid
             * @description Funding Source UUID
             */
            fundingSourceId?: string;
            /** @description Model or Type */
            model?: string;
            /** @description Asset name */
            name?: string;
            /** @description Extra notes */
            notes?: string;
            /** @description Purchase Date */
            purchaseDate?: string;
            /** @description Purchase Price (per unit) */
            purchasePrice?: number;
            /** @description Useful life in months */
            usefulLifeMonths?: number;
        };
        UpdateCategoryDto: {
            /** @example CAT-001 */
            code?: string;
            /** @example 10 */
            depreciationRatePercent?: number;
            /** @example Elektronik */
            name?: string;
        };
        UpdateConditionDto: {
            /** @example COND-GOOD */
            code?: string;
            /** @example true */
            isUsable?: boolean;
            /** @example Baik */
            name?: string;
        };
        UpdateFundingSourceDto: {
            /** @example FUND-GOV */
            code?: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example APBD */
            name?: string;
        };
        UpdateLocationDto: {
            /** @example Gedung Utama */
            building?: string;
            /** @example LOC-A */
            code?: string;
            /** @example Keterangan tambahan */
            description?: string;
            /** @example Gedung Rektorat */
            name?: string;
            /** @example Rak B */
            rack?: string;
            /** @example Ruang 301 */
            room?: string;
        };
        UpdateStatusDto: {
            /** @example true */
            allowTransactions?: boolean;
            /** @example STATUS-ACTIVE */
            code?: string;
            /** @example Aktif */
            name?: string;
            /**
             * @description Protected role of this status in the loan lifecycle (null = custom, no special role).
             * @enum {string|null}
             */
            systemKey?: "AVAILABLE" | "LOANED" | "LOAN_PENDING" | "LOAN_APPROVED" | "LOAN_REJECTED" | "LOAN_RETURNED" | null;
        };
        UpdateUnitDto: {
            /** @description Barcode / QR code */
            barcode?: string;
            /**
             * Format: uuid
             * @description Condition UUID
             */
            conditionId?: string;
            /**
             * Format: uuid
             * @description Custodian user UUID
             */
            custodianId?: string;
            /**
             * Format: uuid
             * @description Location UUID
             */
            locationId?: string;
            /** @description Notes */
            notes?: string;
            /**
             * Format: uuid
             * @description Status UUID
             */
            statusId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            details?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            };
                            /** @example {} */
                            error?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            info?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status?: "ok" | "degraded";
                        };
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                    };
                };
            };
        };
    };
    ApprovalController_findPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApprovalController_process: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveActionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetUnitController_findAll: {
        parameters: {
            query?: {
                /** @description Only units whose status permits transactions — what a loan form needs. Units already reserved by a pending loan, or out on an approved one, hold a status that forbids transactions and are excluded by the same rule. */
                lendable?: boolean;
                limit?: number;
                page?: number;
                /** @description Matches unit number or asset name. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetUnitController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetUnitController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_findAll: {
        parameters: {
            query?: {
                categoryId?: string;
                conditionId?: string;
                fundingSourceId?: string;
                keyword?: string;
                limit?: number;
                locationId?: string;
                page?: number;
                statusId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AssetController_addUnits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CategoryController_getCategories: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryCategoryResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CategoryController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CategoryController_deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoryController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ConditionController_getConditions: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryConditionResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ConditionController_createCondition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConditionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryConditionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ConditionController_deleteCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConditionController_updateCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConditionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryConditionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    FundingSourceController_getFundingSources: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryFundingSourceResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    FundingSourceController_createFundingSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFundingSourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryFundingSourceResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    FundingSourceController_deleteFundingSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FundingSourceController_updateFundingSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFundingSourceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryFundingSourceResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    HistoryController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                unitId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LoanController_findAll: {
        parameters: {
            query?: {
                keyword?: string;
                limit?: number;
                page?: number;
                requesterId?: string;
                statusId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LoanController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoanDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LoanController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LoanController_returnLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnLoanDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LocationController_getLocations: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLocationResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LocationController_createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLocationResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LocationController_deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationController_updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryLocationResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    MetadataController_getMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryMetadataResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    StatusController_getStatuses: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryStatusResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    StatusController_createStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatusDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryStatusResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    StatusController_deleteStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StatusController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryStatusResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkflowController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
}
