/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/employee-positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get employee's position assignments */
        get: operations["EmployeePositionsController_findAll"];
        put?: never;
        /** Assign a position to an employee */
        post: operations["EmployeePositionsController_assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee-positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a position assignment */
        delete: operations["EmployeePositionsController_remove"];
        options?: never;
        head?: never;
        /** Update a position assignment (hireDate / isPrimary) */
        patch: operations["EmployeePositionsController_update"];
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all employees (paginated, searchable) */
        get: operations["EmployeeController_findAll"];
        put?: never;
        /** Create employee (User + Profile in one transaction) */
        post: operations["EmployeeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an employee by ID */
        get: operations["EmployeeController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete an employee (also deactivates User) */
        delete: operations["EmployeeController_remove"];
        options?: never;
        head?: never;
        /** Update employee fields (NIP, NUPTK, employment status) */
        patch: operations["EmployeeController_update"];
        trace?: never;
    };
    "/employees/{id}/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether an employee record exists and is live */
        get: operations["EmployeeInternalController_exists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update employee's profile */
        patch: operations["EmployeeController_updateProfile"];
        trace?: never;
    };
    "/employees/{id}/toggle-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate or deactivate an employee account (without deleting) */
        patch: operations["EmployeeController_toggleActive"];
        trace?: never;
    };
    "/employees/bulk-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview an employee import file (.xlsx): reports per row what would happen, and writes nothing. Post the result to bulk-import/resolve to apply it */
        post: operations["EmployeeImportExportController_bulkImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/bulk-import/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a previewed bulk import: create the new rows, and update or skip each conflicting one as the caller decided */
        post: operations["EmployeeImportExportController_resolveBulkImportConflicts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Employees for a batch of ids
         * @description academic-service holds `employee_id` on teaching assignments and classroom supervisors and renders a name beside each. Ids that match nothing are absent from the response rather than returned as null.
         */
        post: operations["EmployeeInternalController_byIds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/by-user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve an account to its employee record */
        get: operations["EmployeeInternalController_byUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export employees to Excel (.xlsx) */
        get: operations["EmployeeImportExportController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download blank import template (.xlsx) for employees */
        get: operations["EmployeeImportExportController_downloadImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your own employment record — no id parameter exists
         * @description The employment half of a profile screen: employment type, structural positions and hire dates. Who teaches what is academic-service.
         */
        get: operations["EmployeeController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User ids of every employee, for payroll
         * @description Deliberately returns ids alone: the caller resolves names and the active flag from identity-service, so a field added to the employee record here cannot change what payroll reads. Not filtered by position, position category, or employment type (FR-055, FR-056).
         */
        get: operations["EmployeeInternalController_roster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employment-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all employment types (paginated, filterable) */
        get: operations["EmploymentTypeController_findAll"];
        put?: never;
        /** Create a new employment type */
        post: operations["EmploymentTypeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employment-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an employment type by ID */
        get: operations["EmploymentTypeController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete an employment type */
        delete: operations["EmploymentTypeController_remove"];
        options?: never;
        head?: never;
        /** Update an employment type */
        patch: operations["EmploymentTypeController_update"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness probe (DB, memory) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SalaryAssignmentController_list"];
        put?: never;
        /** Set a salary — supersedes rather than overwriting, so an earlier run reproduces */
        post: operations["SalaryAssignmentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SalaryAssignmentController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/assignments/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SalaryAssignmentController_forUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SalaryComponentController_list"];
        put?: never;
        post: operations["SalaryComponentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/components/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Refused while any assignment still uses it */
        delete: operations["SalaryComponentController_remove"];
        options?: never;
        head?: never;
        patch: operations["SalaryComponentController_update"];
        trace?: never;
    };
    "/payroll/payslips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PayslipController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/payslips/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My payslip — resolved from the token, approved runs only */
        get: operations["PayslipController_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PayrollRunController_list"];
        put?: never;
        /** Calculate a closed month into a DRAFT run */
        post: operations["PayrollRunController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PayrollRunController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/runs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Final. An approved run is corrected by adjustment */
        post: operations["PayrollRunController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/runs/{id}/payslips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PayslipController_forRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/runs/{id}/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute a draft and report what moved */
        post: operations["PayrollRunController_recalculate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/runs/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PayrollRunController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all position categories */
        get: operations["PositionCategoryController_findAll"];
        put?: never;
        /** Create a new position category */
        post: operations["PositionCategoryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position-categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get position category by ID */
        get: operations["PositionCategoryController_findOne"];
        put?: never;
        post?: never;
        /** Delete a position category */
        delete: operations["PositionCategoryController_remove"];
        options?: never;
        head?: never;
        /** Update a position category */
        patch: operations["PositionCategoryController_update"];
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all positions (paginated, filterable) */
        get: operations["PositionController_findAll"];
        put?: never;
        /** Create a new position */
        post: operations["PositionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a position by ID */
        get: operations["PositionController_findOne"];
        put?: never;
        post?: never;
        /** Delete a position (only if not in use) */
        delete: operations["PositionController_remove"];
        options?: never;
        head?: never;
        /** Update a position */
        patch: operations["PositionController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BulkImportEmployeeRowDto: {
            birthDate: string;
            birthPlace: string;
            /** Format: email */
            email?: string;
            employmentTypeCode: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE";
            identifier: string;
            name: string;
            nik: string;
            nip?: string;
            nuptk?: string;
            password: string;
            phone?: string;
        };
        BulkImportEmployeeRowResultDto: {
            /** @description The parsed row data, echoed back so the client can resend it to the resolve endpoint without re-parsing the Excel file. */
            data?: components["schemas"]["BulkImportEmployeeRowDto"];
            /**
             * @description Error detail. Present when status is FAILED or CONFLICT.
             * @example Validation failed: identifier must not be empty
             */
            error?: string;
            /** @description Existing employee ID this row conflicts with. */
            existingId?: string;
            /** @example guru001 */
            identifier?: string;
            /**
             * @description Excel row number (1 = header)
             * @example 2
             */
            row: number;
            /**
             * @description CONFLICT means the row matches an existing employee by NIK/NIP/NUPTK. It is not applied automatically — resend it to the resolve endpoint with an "update" or "skip" decision. A taken identifier/username is still a hard FAILED, since it belongs to an unrelated account.
             * @example SUCCESS
             * @enum {string}
             */
            status: "SUCCESS" | "FAILED" | "CONFLICT";
        };
        BulkImportEmployeesResponseDto: {
            /**
             * @description Rows skipped because they match an existing employee.
             * @example 1
             */
            conflict: number;
            /** @example 2 */
            failed: number;
            /** @description Per-row result. Failed rows include row number and error detail. */
            results: components["schemas"]["BulkImportEmployeeRowResultDto"][];
            /** @example 8 */
            success: number;
            /**
             * @description Total rows processed
             * @example 10
             */
            total: number;
        };
        CreateEmployeeDto: {
            /** @example 1980-06-15 */
            birthDate: string;
            /** @example Surabaya */
            birthPlace: string;
            /**
             * Format: email
             * @example budi.santoso@email.com
             */
            email?: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440007
             */
            employmentTypeId: string;
            /**
             * @example MALE
             * @enum {string}
             */
            gender: "MALE" | "FEMALE";
            /**
             * @description Jika kosong, otomatis menggunakan NIP/NUPTK/NIK
             * @example guru001
             */
            identifier?: string;
            /** @example Budi Santoso */
            name: string;
            /** @example 3578010101700001 */
            nik: string;
            /** @example 198006152005011001 */
            nip?: string;
            /** @example 1234567890123456 */
            nuptk?: string;
            /**
             * @description Jika kosong, otomatis menggunakan NIP/NUPTK/NIK
             * @example P@ssw0rd!
             */
            password?: string;
            /** @example 081298765432 */
            phone?: string;
            /**
             * Format: uuid
             * @description Primary position (optional). When set, it is created as the primary EmployeePosition.
             * @example 550e8400-e29b-41d4-a716-446655440099
             */
            positionId?: string;
        };
        CreateEmployeePositionDto: {
            /**
             * @description Hire/assignment date
             * @example 2020-01-01
             */
            hireDate: string;
            /**
             * @default false
             * @example false
             */
            isPrimary: boolean;
            /**
             * Format: uuid
             * @description Position ID (UUID)
             * @example 550e8400-e29b-41d4-a716-446655440007
             */
            positionId: string;
        };
        CreateEmploymentTypeDto: {
            /** @example PNS */
            code: string;
            /** @example Civil Servant */
            name: string;
        };
        CreatePayrollRunDto: {
            /**
             * @default ORIGINAL
             * @enum {string}
             */
            kind: "ORIGINAL" | "ADJUSTMENT";
            /** @example 7 */
            month: number;
            note?: string;
            /** @example 2026 */
            year: number;
        };
        CreatePositionCategoryDto: {
            /** @example MANAGEMENT */
            code: string;
            /** @example Management */
            name: string;
        };
        CreatePositionDto: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440007
             */
            categoryId: string;
            /** @default true */
            isActive: boolean;
            /** @example Kepala Sekolah */
            name: string;
        };
        CreateSalaryAssignmentDto: {
            /**
             * @description For BASE, ALLOWANCE and fixed DEDUCTION.
             * @example 3500000.00
             */
            amount?: string;
            /** Format: uuid */
            componentId: string;
            /**
             * @description Any earlier open assignment is closed the day before this.
             * @example 2026-09-01
             */
            effectiveFrom: string;
            /**
             * @description Per unit of the driver, for any component that has one.
             * @example 150000.00
             */
            rate?: string;
            /** Format: uuid */
            userId: string;
        };
        CreateSalaryComponentDto: {
            /** @example POT_ALPA */
            code: string;
            /**
             * @description Required for ATTENDANCE_DRIVEN, optional for DEDUCTION, else forbidden.
             * @enum {string}
             */
            driver?: "PRESENT_DAYS" | "ABSENT_DAYS" | "LATE_COUNT" | "LATE_MINUTES" | "EARLY_LEAVE_COUNT" | "LEAVE_DAYS" | "OFFICIAL_DUTY_DAYS";
            /** @example Potongan Alpa */
            name: string;
            /** @enum {string} */
            type: "BASE" | "ALLOWANCE" | "ATTENDANCE_DRIVEN" | "DEDUCTION";
        };
        EmployeeExistsResponseDto: {
            /** @description false when missing or soft-deleted */
            data: Record<string, never>;
        };
        EmployeeIdByUserResponseDto: {
            /** @description null when the account owns no employee record */
            data: string | null;
        };
        EmployeeIdsDto: {
            ids: string[];
        };
        EmployeeListResponseDto: {
            data: components["schemas"]["EmployeeResponseDto"][];
            /**
             * @example {
             *       "page": 1,
             *       "limit": 10,
             *       "total": 50,
             *       "totalPages": 5
             *     }
             */
            meta: Record<string, never>;
        };
        EmployeePositionResponseDto: {
            /** @example 2020-01-01 */
            hireDate: string;
            /** @example 550e8400-e29b-41d4-a716-446655440002 */
            id: string;
            /** @example false */
            isPrimary: boolean;
            /**
             * @description Position UUID
             * @example 550e8400-e29b-41d4-a716-446655440002
             */
            positionId: string;
        };
        EmployeeRefDto: {
            id: string;
            nip: Record<string, never> | null;
            /** @description The employee's account, so the caller resolves the name against identity-service rather than against this service. */
            userId: string;
        };
        EmployeeRefListResponseDto: {
            data: components["schemas"]["EmployeeRefDto"][];
        };
        EmployeeResponseDto: {
            employmentType: components["schemas"]["EmploymentTypeResponseDto"];
            /** @example 550e8400-e29b-41d4-a716-446655440002 */
            id: string;
            /** @example true */
            isActive: boolean;
            /** @example 198006152005011001 */
            nip?: string | null;
            /** @example 1234567890123456 */
            nuptk?: string | null;
            profile: components["schemas"]["ProfileResponseDto"];
        };
        EmployeeRosterResponseDto: {
            /**
             * @description User ids of every employee on the books, soft-deleted ones excluded. Not filtered by position, position category, or employment type.
             * @example [
             *       "0f8c3b3e-4a4f-4a3a-9a7a-2c5f6b1d9e10"
             *     ]
             */
            data: string[];
        };
        EmploymentTypeListResponseDto: {
            data: components["schemas"]["EmploymentTypeResponseDto"][];
            /**
             * @example {
             *       "page": 1,
             *       "limit": 10,
             *       "total": 5,
             *       "totalPages": 1
             *     }
             */
            meta: Record<string, never>;
        };
        EmploymentTypeResponseDto: {
            /** @example PNS */
            code: string;
            /** @example 550e8400-e29b-41d4-a716-446655440007 */
            id: string;
            /** @example Civil Servant */
            name: string;
        };
        PayslipAttendanceResponseDto: {
            absentDays: number;
            earlyLeaveCount: number;
            lateCount: number;
            lateMinutes: number;
            leaveDays: number;
            officialDutyDays: number;
            presentDays: number;
        };
        PayslipEmployeeResponseDto: {
            displayName?: string | null;
            identifier: string;
            /** Format: uuid */
            userId: string;
        };
        PayslipLineResponseDto: {
            /** @example 3500000 */
            amount: string;
            componentCode: string;
            componentName: string;
            /** @enum {string} */
            componentType: "BASE" | "ALLOWANCE" | "ATTENDANCE_DRIVEN" | "DEDUCTION";
            /** @enum {string|null} */
            driver?: "PRESENT_DAYS" | "ABSENT_DAYS" | "LATE_COUNT" | "LATE_MINUTES" | "EARLY_LEAVE_COUNT" | "LEAVE_DAYS" | "OFFICIAL_DUTY_DAYS" | null;
            /** @example 3 */
            driverCount?: number | null;
            /** @example 150000 */
            rate?: string | null;
        };
        PayslipResponseDto: {
            attendance: components["schemas"]["PayslipAttendanceResponseDto"];
            /** @example 150000 */
            deductions: string;
            employee: components["schemas"]["PayslipEmployeeResponseDto"];
            /** @example 3650000 */
            gross: string;
            /** Format: uuid */
            id: string;
            lines: components["schemas"]["PayslipLineResponseDto"][];
            /** @example 3500000 */
            net: string;
            run: components["schemas"]["PayslipRunResponseDto"];
        };
        PayslipRunResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "ORIGINAL" | "ADJUSTMENT";
            month: number;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED" | "APPROVED";
            year: number;
        };
        PayslipSummaryResponseDto: {
            /** @example 150000 */
            deductions: string;
            employee: components["schemas"]["PayslipEmployeeResponseDto"];
            /** @example 3650000 */
            gross: string;
            /** Format: uuid */
            id: string;
            /** @example 3500000 */
            net: string;
        };
        PositionCategoryListResponseDto: {
            data: components["schemas"]["PositionCategoryResponseDto"][];
            /**
             * @example {
             *       "page": 1,
             *       "limit": 10,
             *       "total": 4,
             *       "totalPages": 1
             *     }
             */
            meta: Record<string, never>;
        };
        PositionCategoryResponseDto: {
            /** @example MANAGEMENT */
            code: string;
            /** @example 550e8400-e29b-41d4-a716-446655440007 */
            id: string;
            /** @example Management */
            name: string;
        };
        PositionListResponseDto: {
            data: components["schemas"]["PositionResponseDto"][];
            /**
             * @example {
             *       "page": 1,
             *       "limit": 10,
             *       "total": 15,
             *       "totalPages": 2
             *     }
             */
            meta: Record<string, never>;
        };
        PositionResponseDto: {
            category: components["schemas"]["PositionCategoryResponseDto"];
            /** @example 550e8400-e29b-41d4-a716-446655440007 */
            id: string;
            /** @example true */
            isActive: boolean;
            /** @example Kepala Sekolah */
            name: string;
        };
        ProfileResponseDto: {
            /** @description Signed, time-limited profile photo URL (bucket is private) */
            avatar?: string | null;
            /** @example 2008-01-01 */
            birthDate: string;
            /** @example Malang */
            birthPlace: string;
            /** @example ahmad.fauzi@email.com */
            email?: string | null;
            /**
             * @example MALE
             * @enum {string}
             */
            gender: "MALE" | "FEMALE";
            /**
             * Format: uuid
             * @description Profile ID
             * @example 550e8400-e29b-41d4-a716-446655440015
             */
            id: string;
            /** @example Ahmad Fauzi */
            name: string;
            /** @example 3578010101080001 */
            nik: string;
            /** @example 081234567890 */
            phone?: string | null;
            /**
             * Format: uuid
             * @description Owner user ID
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            userId: string;
        };
        ResolveBulkImportConflictDto: {
            /** @enum {string} */
            action: "update" | "skip";
            data: components["schemas"]["BulkImportEmployeeRowDto"];
            /**
             * Format: uuid
             * @description Existing employee ID this row conflicts with
             */
            existingId?: string;
        };
        ResolveBulkImportConflictsDto: {
            conflicts: components["schemas"]["ResolveBulkImportConflictDto"][];
        };
        ResolveBulkImportErrorDto: {
            error: string;
            existingId: string;
        };
        ResolveBulkImportResponseDto: {
            errors: components["schemas"]["ResolveBulkImportErrorDto"][];
            /**
             * @description Rows that threw while processing
             * @example 0
             */
            failed: number;
            /**
             * @description Rows the caller chose to skip
             * @example 2
             */
            skipped: number;
            /**
             * @description Total rows submitted
             * @example 5
             */
            total: number;
            /**
             * @description Rows created or updated
             * @example 3
             */
            updated: number;
        };
        UpdateEmployeeDto: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440007
             */
            employmentTypeId?: string;
            /** @example 198006152005011001 */
            nip?: string;
            /** @example 1234567890123456 */
            nuptk?: string;
        };
        UpdateEmployeePositionDto: {
            /** @example 2020-01-01 */
            hireDate?: string;
            /** @example false */
            isPrimary?: boolean;
        };
        UpdateEmploymentTypeDto: {
            /** @example Civil Servant Update */
            name?: string;
        };
        UpdatePositionCategoryDto: {
            /** @example Management Updated */
            name?: string;
        };
        UpdatePositionDto: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440007
             */
            categoryId?: string;
            /** @default true */
            isActive: boolean;
            /** @example Kepala Sekolah */
            name?: string;
        };
        UpdateProfileDto: {
            /** @example 2008-01-01 */
            birthDate?: string;
            /** @example Malang */
            birthPlace?: string;
            /**
             * @description Golongan Darah ID
             * @example blood-type-uuid
             */
            bloodTypeId?: string;
            /**
             * Format: email
             * @example ahmad.fauzi@email.com
             */
            email?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /**
             * @description Status Pernikahan
             * @enum {string}
             */
            maritalStatus?: "SINGLE" | "MARRIED" | "DIVORCED" | "WIDOWED";
            /** @example Ahmad Fauzi */
            name?: string;
            /** @example 3578010101080001 */
            nik?: string;
            /**
             * @description No. KK (16 digit)
             * @example 3578010101080001
             */
            noKk?: string;
            /**
             * @description NPWP
             * @example 12.345.678.9-012.000
             */
            npwp?: string;
            /** @example 081234567890 */
            phone?: string;
            /**
             * @description Agama ID
             * @example religion-uuid
             */
            religionId?: string;
        };
        UpdateSalaryComponentDto: {
            /** @example POT_ALPA */
            code?: string;
            /**
             * @description Required for ATTENDANCE_DRIVEN, optional for DEDUCTION, else forbidden.
             * @enum {string}
             */
            driver?: "PRESENT_DAYS" | "ABSENT_DAYS" | "LATE_COUNT" | "LATE_MINUTES" | "EARLY_LEAVE_COUNT" | "LEAVE_DAYS" | "OFFICIAL_DUTY_DAYS";
            /** @description Deactivating stops new assignments */
            isActive?: boolean;
            /** @example Potongan Alpa */
            name?: string;
            /** @enum {string} */
            type?: "BASE" | "ALLOWANCE" | "ATTENDANCE_DRIVEN" | "DEDUCTION";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    EmployeePositionsController_findAll: {
        parameters: {
            query: {
                employeeId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeePositionResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeePositionsController_assign: {
        parameters: {
            query: {
                employeeId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeePositionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeePositionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Position is inactive */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee or position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Same position already assigned on that date */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeePositionsController_remove: {
        parameters: {
            query: {
                employeeId: string;
            };
            header?: never;
            path: {
                /** @description EmployeePosition link ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeePositionsController_update: {
        parameters: {
            query: {
                employeeId: string;
            };
            header?: never;
            path: {
                /** @description EmployeePosition link ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeePositionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeePositionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Assignment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by academic year ID — shows employees with class supervisor or subject assignment in that year */
                academicYearId?: string;
                /** @description Filter by employment type ID */
                employmentTypeId?: string;
                /** @description Filter by active status (user.isActive) */
                isActive?: boolean;
                limit?: number;
                page?: number;
                /** @description Filter by position category ID (primary position) */
                positionCategoryId?: string;
                /** @description Search by name, NIP, or NUPTK */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /**
                         * @example {
                         *       "page": 1,
                         *       "limit": 10,
                         *       "total": 50,
                         *       "totalPages": 5
                         *     }
                         */
                        meta?: Record<string, never>;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate identifier / NIK / NIP / NUPTK */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeInternalController_exists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeExistsResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate NIK */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_toggleActive: {
        parameters: {
            query: {
                isActive: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeImportExportController_bulkImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["BulkImportEmployeesResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Invalid file or empty sheet */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeImportExportController_resolveBulkImportConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveBulkImportConflictsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ResolveBulkImportResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    EmployeeInternalController_byIds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeIdsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeRefListResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeInternalController_byUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeIdByUserResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeImportExportController_export: {
        parameters: {
            query?: {
                /** @description Filter by employment type ID */
                employmentTypeId?: string;
                /** @description Filter by active status */
                isActive?: boolean;
                /** @description Search by name, NIP, or NUPTK */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns an Excel file as attachment */
            200: {
                headers: {
                    /** @description attachment; filename="employees.xlsx" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeImportExportController_downloadImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a blank Excel template file */
            200: {
                headers: {
                    /** @description attachment; filename="template_import_pegawai.xlsx" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Not linked to an employee record */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeeInternalController_roster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmployeeRosterResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmploymentTypeController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                /** @description Search by name or code */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of employment types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmploymentTypeResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /**
                         * @example {
                         *       "page": 1,
                         *       "limit": 10,
                         *       "total": 5,
                         *       "totalPages": 1
                         *     }
                         */
                        meta?: Record<string, never>;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmploymentTypeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmploymentTypeDto"];
            };
        };
        responses: {
            /** @description Employment type created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmploymentTypeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employment type code already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmploymentTypeController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employment type details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmploymentTypeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employment type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmploymentTypeController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employment type deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employment type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employment type is in use and cannot be deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmploymentTypeController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmploymentTypeDto"];
            };
        };
        responses: {
            /** @description Employment type updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["EmploymentTypeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employment type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Liveness and readiness check passed
             *
             *     The Health Check is successful
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            details?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            };
                            /** @example {} */
                            error?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            info?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status?: "ok" | "degraded";
                        };
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /**
             * @description Health check failed
             *
             *     The Health Check is not successful
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                    };
                };
            };
        };
    };
    SalaryAssignmentController_list: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryAssignmentController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSalaryAssignmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryAssignmentController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryAssignmentController_forUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryComponentController_list: {
        parameters: {
            query?: {
                includeInactive?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryComponentController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSalaryComponentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryComponentController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    SalaryComponentController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSalaryComponentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayslipController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PayslipResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayslipController_mine: {
        parameters: {
            query?: {
                month?: number;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PayslipResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayrollRunController_list: {
        parameters: {
            query?: {
                status?: "DRAFT" | "SUBMITTED" | "APPROVED";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayrollRunController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePayrollRunDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayrollRunController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayrollRunController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayslipController_forRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PayslipSummaryResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayrollRunController_recalculate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PayrollRunController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PositionCategoryController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                /** @description Search by name or code */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionCategoryResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /**
                         * @example {
                         *       "page": 1,
                         *       "limit": 10,
                         *       "total": 4,
                         *       "totalPages": 1
                         *     }
                         */
                        meta?: Record<string, never>;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PositionCategoryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePositionCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Duplicate code */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionCategoryController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Position category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionCategoryController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Still in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionCategoryController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePositionCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionCategoryResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Position category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by category ID */
                categoryId?: string;
                /** @description Filter by active status */
                isActive?: boolean;
                limit?: number;
                page?: number;
                /** @description Search by name */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /**
                         * @example {
                         *       "page": 1,
                         *       "limit": 10,
                         *       "total": 15,
                         *       "totalPages": 2
                         *     }
                         */
                        meta?: Record<string, never>;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    PositionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePositionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Duplicate position name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Position deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position still in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePositionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PositionResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate position name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
