export enum AcademicCalendarType {
  SEMESTER_START = 'SEMESTER_START',
  SEMESTER_END = 'SEMESTER_END',
  EXAM_MID = 'EXAM_MID',
  EXAM_FINAL = 'EXAM_FINAL',
  REGISTRATION = 'REGISTRATION',
  HOLIDAY_NATIONAL = 'HOLIDAY_NATIONAL',
  HOLIDAY_WEEKLY = 'HOLIDAY_WEEKLY',
  HOLIDAY_SCHOOL = 'HOLIDAY_SCHOOL',
  STUDY = 'STUDY',
  OTHER = 'OTHER',
}
