export {
  IApprovalRepository,
  IApprovalCapabilityPort,
  type ApprovalWorkflowStepRepositoryOutput,
  type ApprovalWorkflowRepositoryOutput,
  type ApprovalLogRepositoryOutput,
  type ApprovalConsequenceType,
  type ApprovalConsequenceStatus,
  type ApprovalConsequenceTransitionResult,
  type ProcessApprovalConsequence,
  type ApprovalInstanceRepositoryOutput,
  type CreateApprovalWorkflowStepInput,
  type CreateApprovalWorkflowInput,
  type UpdateApprovalInstanceInput,
  type CreateApprovalLogInput,
  type ProcessApprovalLocalTransactionInput,
  type ProcessApprovalResult,
  type ApprovalStatusRepositoryOutput,
  type ApprovalWorkflowCapabilityOutput,
  type CreateApprovalInstanceCapabilityInput,
  type ApprovalInstanceCapabilityOutput,
} from './domain/repositories/approval.repository.js'
