/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admissions/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published announcements for my wave (or global) */
        get: operations["AdmissionApplicantController_getAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications (paginated, filterable) */
        get: operations["AdmissionAdminController_findAll"];
        put?: never;
        /** Create an applicant account and a DRAFT application */
        post: operations["AdmissionAdminRegistrationController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application detail (form, documents, payment) */
        get: operations["AdmissionAdminController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the application */
        post: operations["AdmissionAdminController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/documents/{docId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve or reject a document */
        patch: operations["AdmissionAdminController_verifyDocument"];
        trace?: never;
    };
    "/admissions/applications/{id}/documents/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a required document for an application */
        put: operations["AdmissionAdminRegistrationController_uploadDocument"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provision the accepted applicant as a student */
        post: operations["AdmissionAdminController_enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Fill a step of an application on behalf of its owner */
        patch: operations["AdmissionAdminRegistrationController_updateForm"];
        trace?: never;
    };
    "/admissions/applications/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload payment proof for an application */
        put: operations["AdmissionAdminRegistrationController_uploadPaymentProof"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/payment/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Verify or reject the payment proof */
        patch: operations["AdmissionAdminController_verifyPayment"];
        trace?: never;
    };
    "/admissions/applications/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject the application */
        post: operations["AdmissionAdminController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/request-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return the application to the applicant for revision */
        post: operations["AdmissionAdminController_requestRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an application on behalf of its owner */
        post: operations["AdmissionAdminRegistrationController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/applications/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark application VERIFIED (all docs approved + payment verified) */
        post: operations["AdmissionAdminController_verifyApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/manage-announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List admission announcements (admin) */
        get: operations["AdmissionAnnouncementController_findAll"];
        put?: never;
        /** Create an admission announcement */
        post: operations["AdmissionAnnouncementController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/manage-announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete an admission announcement */
        delete: operations["AdmissionAnnouncementController_remove"];
        options?: never;
        head?: never;
        /** Update an admission announcement */
        patch: operations["AdmissionAnnouncementController_update"];
        trace?: never;
    };
    "/admissions/manage-announcements/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish + notify applicants in scope */
        post: operations["AdmissionAnnouncementController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/my-application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my application (form, documents, payment, wave) */
        get: operations["AdmissionApplicantController_getMyApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update my application form (partial, per wizard step) */
        patch: operations["AdmissionApplicantController_updateMyApplication"];
        trace?: never;
    };
    "/admissions/my-application/documents/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload (or replace) a required document */
        put: operations["AdmissionApplicantController_uploadDocument"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/my-application/ensure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ensure my application exists (idempotent) */
        post: operations["AdmissionApplicantController_ensureMyApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/my-application/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My notifications (latest 50, with unread count) */
        get: operations["AdmissionNotificationController_getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/my-application/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload payment transfer proof */
        put: operations["AdmissionApplicantController_uploadPaymentProof"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/my-application/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit my application for verification */
        post: operations["AdmissionApplicantController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read */
        patch: operations["AdmissionNotificationController_markRead"];
        trace?: never;
    };
    "/admissions/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all my notifications as read */
        patch: operations["AdmissionNotificationController_markAllRead"];
        trace?: never;
    };
    "/admissions/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new applicant account */
        post: operations["AdmissionPublicController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admission statistics per status and wave */
        get: operations["AdmissionAdminController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List admission waves */
        get: operations["AdmissionWaveController_findAll"];
        put?: never;
        /** Create an admission wave */
        post: operations["AdmissionWaveController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/waves/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an admission wave */
        get: operations["AdmissionWaveController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete an admission wave (no applicants only) */
        delete: operations["AdmissionWaveController_remove"];
        options?: never;
        head?: never;
        /** Update an admission wave */
        patch: operations["AdmissionWaveController_update"];
        trace?: never;
    };
    "/admissions/waves/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active admission waves with requirements (landing page) */
        get: operations["AdmissionPublicController_getActiveWaves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness probe (DB, memory) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptApplicationDto: {
            note?: string;
        };
        ApplicationDetailResponseDto: {
            /**
             * Format: date-time
             * @example null
             */
            birthDate?: string | null;
            /** @example null */
            birthPlace?: string | null;
            /** @example null */
            city?: string | null;
            /** @example null */
            district?: string | null;
            documents: components["schemas"]["ApplicationDocumentResponseDto"][];
            documentTypes?: components["schemas"]["ApplicationDocumentTypeResponseDto"][];
            /** @example null */
            email?: string | null;
            /** @example Ahmad Fauzi */
            fullName: string;
            /** @example null */
            gender?: string | null;
            /** Format: uuid */
            id: string;
            /** @example null */
            nickname?: string | null;
            /** @example null */
            nik?: string | null;
            /** @example null */
            nisn?: string | null;
            parents: components["schemas"]["ApplicationParentResponseDto"][];
            payment?: components["schemas"]["ApplicationPaymentResponseDto"] | null;
            /** @example null */
            phone?: string | null;
            /** @example null */
            postalCode?: string | null;
            /** @example null */
            province?: string | null;
            /** @example PSB-2026-0001 */
            registrationNumber: string;
            /** @example null */
            revisionNote?: string | null;
            /** @example null */
            rt?: string | null;
            /** @example null */
            rw?: string | null;
            /** @example DRAFT */
            status: string;
            /** @example null */
            street?: string | null;
            /**
             * Format: date-time
             * @example null
             */
            submittedAt?: string | null;
            /** Format: uuid */
            userId: string;
            /** @example null */
            village?: string | null;
            wave: components["schemas"]["ApplicationWaveResponseDto"];
            /** Format: uuid */
            waveId: string;
        };
        ApplicationDocumentResponseDto: {
            /** Format: uuid */
            applicationId: string;
            documentType: components["schemas"]["ApplicationDocumentTypeResponseDto"];
            /** Format: uuid */
            documentTypeId: string;
            file?: components["schemas"]["ApplicationFileResponseDto"] | null;
            /** Format: uuid */
            id: string;
            /** @example null */
            note?: string | null;
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "APPROVED" | "REJECTED";
            /**
             * Format: date-time
             * @example null
             */
            verifiedAt?: string | null;
        };
        ApplicationDocumentTypeResponseDto: {
            /** @example KK */
            code: string;
            /** Format: uuid */
            id: string;
            /** @example true */
            isActive: boolean;
            /** @example true */
            isRequired: boolean;
            /** @example Kartu Keluarga */
            name: string;
            /** @example 1 */
            sortOrder: number;
        };
        ApplicationFileResponseDto: {
            /** @example 1758000000000-kk.png */
            filename: string;
            /** Format: uuid */
            id: string;
            /** @example image/png */
            mimeType: string;
            /** @example kk.png */
            originalName: string;
            /** @example 204800 */
            sizeBytes: number;
            /** @example documents/Kartu Keluarga/1758000000000-kk.png */
            storageKey: string;
        };
        ApplicationParentResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example true */
            isPrimary: boolean;
            /** @example Budi Santoso */
            name: string;
            /** @example null */
            nik?: string | null;
            /** @example null */
            phone?: string | null;
            /**
             * @example FATHER
             * @enum {string}
             */
            relation: "FATHER" | "MOTHER" | "GUARDIAN";
        };
        ApplicationPaymentResponseDto: {
            /** @example 250000 */
            amount: number;
            /** Format: uuid */
            applicationId: string;
            /** @example BSI */
            bankName?: string | null;
            /** Format: uuid */
            id: string;
            /** @example null */
            note?: string | null;
            proofFile?: components["schemas"]["ApplicationFileResponseDto"] | null;
            /** Format: uuid */
            proofFileId?: string | null;
            /** @example Ahmad Fauzi */
            senderAccountName?: string | null;
            /**
             * @example UNPAID
             * @enum {string}
             */
            status: "UNPAID" | "PENDING" | "VERIFIED" | "REJECTED";
            /**
             * Format: date-time
             * @example 2026-07-01
             */
            transferDate?: string | null;
        };
        ApplicationWaveResponseDto: {
            /** @example GEL-1 */
            code: string;
            /** Format: uuid */
            id: string;
            /** @example Gelombang 1 */
            name: string;
            /** @example 250000 */
            registrationFee: number;
        };
        CreateAdmissionAnnouncementDto: {
            content: string;
            /** @default false */
            isPublished: boolean;
            /** @example Pengumuman Hasil Seleksi Gelombang 1 */
            title: string;
            /**
             * Format: uuid
             * @description Target wave; empty = all waves
             */
            waveId?: string;
        };
        CreateAdmissionWaveDto: {
            /** Format: uuid */
            academicYearId: string;
            /** @example G1-2026 */
            code: string;
            description?: string;
            /** Format: date */
            endDate: string;
            /** @default true */
            isActive: boolean;
            /** @example Gelombang 1 — 2026/2027 */
            name: string;
            /** @example 100 */
            quota: number;
            /** @example 250000 */
            registrationFee: number;
            /** Format: date */
            startDate: string;
        };
        EnrollApplicantDto: {
            /**
             * Format: uuid
             * @description When set, the student is enrolled into this classroom for the active semester
             */
            classroomId?: string;
            /**
             * Format: uuid
             * @description Grade level of the student (required)
             */
            gradeId: string;
            /** @example 20260001 */
            nis: string;
            /** @example 0091234567 */
            nisn: string;
        };
        PublicRegisterApplicantDto: {
            /**
             * Format: email
             * @example ahmad@example.com
             */
            email: string;
            /** @example Ahmad Fauzi */
            fullName: string;
            password: string;
            passwordConfirm: string;
            /** @example 081234567890 */
            phone?: string;
        };
        RegisterApplicantDto: {
            /**
             * Format: email
             * @example ahmad@example.com
             */
            email: string;
            /** @example Ahmad Fauzi */
            fullName: string;
            password: string;
            passwordConfirm: string;
            /** @example 081234567890 */
            phone?: string;
            /** Format: uuid */
            waveId: string;
        };
        RegisteredApplicantResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example ahmad@example.com */
            identifier: string;
            /** @example PSB-2026-0001 */
            registrationNumber: string;
        };
        RejectApplicationDto: {
            /** @description Alasan penolakan */
            reason: string;
        };
        RequestRevisionDto: {
            /** @description Revision note shown to the applicant */
            note: string;
        };
        UpdateAdmissionAnnouncementDto: {
            content?: string;
            /** @default false */
            isPublished: boolean;
            /** @example Pengumuman Hasil Seleksi Gelombang 1 */
            title?: string;
            /**
             * Format: uuid
             * @description Target wave; empty = all waves
             */
            waveId?: string;
        };
        UpdateAdmissionWaveDto: {
            /** Format: uuid */
            academicYearId?: string;
            /** @example G1-2026 */
            code?: string;
            description?: string;
            /** Format: date */
            endDate?: string;
            /** @default true */
            isActive: boolean;
            /** @example Gelombang 1 — 2026/2027 */
            name?: string;
            /** @example 100 */
            quota?: number;
            /** @example 250000 */
            registrationFee?: number;
            /** Format: date */
            startDate?: string;
        };
        UpdateApplicationParentDto: {
            /** Format: date */
            birthDate?: string;
            birthPlace?: string;
            /** Format: uuid */
            educationId?: string;
            /** @enum {string} */
            income?: "BELOW_500K" | "BETWEEN_500K_1M" | "BETWEEN_1M_2M" | "BETWEEN_2M_3M" | "ABOVE_3M";
            isPrimary?: boolean;
            name?: string;
            nik?: string;
            /** Format: uuid */
            occupationId?: string;
            phone?: string;
            /** @enum {string} */
            relation?: "FATHER" | "MOTHER" | "GUARDIAN";
        };
        UpdateMyApplicationDto: {
            /** Format: date */
            birthDate?: string;
            birthPlace?: string;
            childOrder?: number;
            city?: string;
            district?: string;
            fullName?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            graduationYear?: number;
            nickname?: string;
            nik?: string;
            nisn?: string;
            parents?: components["schemas"]["UpdateApplicationParentDto"][];
            phone?: string;
            postalCode?: string;
            previousSchoolAddress?: string;
            previousSchoolName?: string;
            previousSchoolNpsn?: string;
            province?: string;
            /** Format: uuid */
            religionId?: string;
            rt?: string;
            rw?: string;
            siblingCount?: number;
            street?: string;
            village?: string;
        };
        UploadPaymentProofDto: {
            /** @example BSI */
            bankName: string;
            /** @example Ahmad Fauzi */
            senderAccountName: string;
            /** Format: date */
            transferDate?: string;
        };
        VerifyDocumentDto: {
            /** @description Required when the decision is REJECTED */
            note?: string;
            /** @enum {string} */
            status: "APPROVED" | "REJECTED";
        };
        VerifyPaymentDto: {
            /** @description Required when the decision is REJECTED */
            note?: string;
            /** @enum {string} */
            status: "VERIFIED" | "REJECTED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdmissionApplicantController_getAnnouncements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                /** @description Search by name, registration number, or email */
                search?: string;
                status?: "DRAFT" | "SUBMITTED" | "REVISION_NEEDED" | "VERIFIED" | "ACCEPTED" | "ENROLLING" | "REJECTED" | "ENROLLED";
                waveId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminRegistrationController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterApplicantDto"];
            };
        };
        responses: {
            /** @description Applicant registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["RegisteredApplicantResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptApplicationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminController_verifyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                docId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminRegistrationController_uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApplicationDocumentResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminController_enroll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollApplicantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description NIS/NISN/NIK conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminRegistrationController_updateForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyApplicationDto"];
            };
        };
        responses: {
            /** @description Application detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApplicationDetailResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Not editable in current status */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminRegistrationController_uploadPaymentProof: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadPaymentProofDto"];
            };
        };
        responses: {
            /** @description Payment proof uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApplicationPaymentResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminController_verifyPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectApplicationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminController_requestRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestRevisionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAdminRegistrationController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application submitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApplicationDetailResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Incomplete data or documents */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminController_verifyApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAnnouncementController_findAll: {
        parameters: {
            query?: {
                isPublished?: boolean;
                limit?: number;
                page?: number;
                search?: string;
                waveId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAnnouncementController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdmissionAnnouncementDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAnnouncementController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAnnouncementController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdmissionAnnouncementDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionAnnouncementController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionApplicantController_getMyApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No application for this account */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionApplicantController_updateMyApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyApplicationDto"];
            };
        };
        responses: {
            /** @description Application updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not editable in current status */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionApplicantController_uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionApplicantController_ensureMyApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application already existed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApplicationDetailResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Application created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ApplicationDetailResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Registration is not open */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionNotificationController_getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionApplicantController_uploadPaymentProof: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadPaymentProofDto"];
            };
        };
        responses: {
            /** @description Payment proof uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionApplicantController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application submitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Incomplete data or documents */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionNotificationController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionNotificationController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionPublicController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicRegisterApplicantDto"];
            };
        };
        responses: {
            /** @description Applicant registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wave closed or invalid data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionAdminController_getStats: {
        parameters: {
            query?: {
                waveId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionWaveController_findAll: {
        parameters: {
            query?: {
                academicYearId?: string;
                isActive?: boolean;
                limit?: number;
                page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionWaveController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdmissionWaveDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionWaveController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionWaveController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdmissionWaveController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdmissionWaveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AdmissionPublicController_getActiveWaves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active waves and document requirements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            details?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            };
                            /** @example {} */
                            error?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            info?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status?: "ok" | "degraded";
                        };
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                    };
                };
            };
        };
    };
}
