/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/daily-presences/by-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One day's gate record for a batch of accounts
         * @description Pre-fills a class attendance sheet from the gate. Accounts with no record that day are absent from the response rather than defaulted.
         */
        post: operations["DailyRecordInternalController_byUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-presences/monthly-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One month's gate totals for a batch of accounts
         * @description Every account asked for appears, including one with no record at all — a defensible figure for someone on long leave, not a silent omission.
         */
        post: operations["DailyRecordInternalController_monthlySummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness probe (DB, memory) */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cards (never returns the card code) */
        get: operations["CredentialController_list"];
        put?: never;
        /** Issue a card — the code is returned once */
        post: operations["CredentialController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CredentialController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/credentials/{id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace a lost card — history stays continuous */
        post: operations["CredentialController_replaceCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/credentials/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a card — ends the holder’s expected days */
        post: operations["CredentialController_revokeCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/credentials/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Card codes for a print run */
        get: operations["CredentialController_print"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/daily-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A day's attendance for everyone */
        get: operations["DailyRecordController_list"];
        put?: never;
        /** Record a day by hand for someone who never scanned */
        post: operations["DailyRecordController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/daily-records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One day, with its full correction trail */
        get: operations["DailyRecordController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct a day — a reason is required and you cannot edit your own */
        patch: operations["DailyRecordController_update"];
        trace?: never;
    };
    "/presence/daily-records/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own attendance for a month */
        get: operations["DailyRecordController_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/daily-records/recap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly recap per person */
        get: operations["DailyRecordController_recap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/daily-records/recap/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The same figures as the recap, for a spreadsheet */
        get: operations["DailyRecordController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gate devices with their last-seen time */
        get: operations["DeviceController_list"];
        put?: never;
        /** Register a gate — the token is shown once */
        post: operations["DeviceController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Retire a gate — its scan history is kept */
        delete: operations["DeviceController_remove"];
        options?: never;
        head?: never;
        patch: operations["DeviceController_update"];
        trace?: never;
    };
    "/presence/devices/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a new token — the old one stops working */
        post: operations["DeviceController_rotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-balances/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeaveController_balancesFor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-balances/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeaveController_myBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeaveController_listRequests"];
        put?: never;
        /** Submit leave — only working days consume quota */
        post: operations["LeaveController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve — refused for your own request, or over quota */
        post: operations["LeaveController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LeaveController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-requests/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw your own pending request — consumes no quota */
        post: operations["LeaveController_withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-requests/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own requests — no user parameter exists */
        get: operations["LeaveController_myRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeaveTypeController_list"];
        put?: never;
        post: operations["LeaveTypeController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/leave-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["LeaveTypeController_remove"];
        options?: never;
        head?: never;
        patch: operations["LeaveTypeController_edit"];
        trace?: never;
    };
    "/presence/non-working-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkPatternController_listHolidays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/non-working-days/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["WorkPatternController_removeHoliday"];
        options?: never;
        head?: never;
        patch: operations["WorkPatternController_renameHoliday"];
        trace?: never;
    };
    "/presence/non-working-days/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add holidays previewed by the operator */
        post: operations["WorkPatternController_bulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Periods that have been closed */
        get: operations["AttendancePeriodController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/periods/{year}/{month}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a month — refused while any day still lacks a check-out */
        post: operations["AttendancePeriodController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/periods/{year}/{month}/closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether an attendance month is closed */
        get: operations["AttendancePeriodInternalController_isClosed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The scan log, including rejected attempts */
        get: operations["ScanController_list"];
        put?: never;
        /** Record one scan from a gate device */
        post: operations["ScanController_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/scans/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flush scans queued while the device was offline */
        post: operations["ScanController_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/scans/clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The anchor a device pins its monotonic clock to */
        get: operations["ScanController_clock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/student-absences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a student excused absence */
        post: operations["LeaveController_recordStudentAbsence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/work-pattern-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkPatternController_listAssignments"];
        put?: never;
        post: operations["WorkPatternController_assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/work-patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkPatternController_listPatterns"];
        put?: never;
        post: operations["WorkPatternController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence/work-patterns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["WorkPatternController_remove"];
        options?: never;
        head?: never;
        /** Edit a pattern — closed periods keep the figures they were judged with */
        patch: operations["WorkPatternController_update"];
        trace?: never;
    };
    "/presence/work-patterns/{id}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace all seven weekdays atomically */
        put: operations["WorkPatternController_putDays"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssignWorkPatternDto: {
            /**
             * @description Any earlier open assignment is closed the day before this.
             * @example 2026-09-01
             */
            effectiveFrom: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            workPatternId: string;
        };
        AttendancePeriodClosedDto: {
            /** @description Whether the month is closed. Payroll refuses to run against an open month, because a scan recorded afterwards would change a payslip already issued. */
            closed: boolean;
        };
        AttendancePeriodClosedResponseDto: {
            data: components["schemas"]["AttendancePeriodClosedDto"];
        };
        BulkNonWorkingDaysDto: {
            days: components["schemas"]["NonWorkingDayDto"][];
        };
        CreateDailyPresenceDto: {
            checkInAt?: string;
            checkOutAt?: string;
            /** @example 2026-08-10 */
            date: string;
            note?: string;
            /** @example Lupa membawa kartu, hadir sesuai jadwal */
            reason: string;
            /** @enum {string} */
            status: "PRESENT" | "LATE" | "ABSENT" | "ON_LEAVE" | "OFFICIAL_DUTY" | "NOT_EXPECTED";
            /** @enum {string} */
            subjectType: "STUDENT" | "EMPLOYEE";
            /** Format: uuid */
            userId: string;
        };
        CreateLeaveTypeDto: {
            /** @example 12 */
            annualQuota?: number;
            /** @enum {string} */
            appliesTo: "STUDENT" | "EMPLOYEE";
            /** @example CUTI_MELAHIRKAN */
            code: string;
            consumesQuota: boolean;
            /** @example Cuti Melahirkan */
            name: string;
            requiresDocument: boolean;
            /**
             * @description OFFICIAL_DUTY means working elsewhere — it must not read as leave in a recap.
             * @enum {string}
             */
            treatment: "ON_LEAVE" | "OFFICIAL_DUTY";
        };
        CreateWorkPatternDto: {
            /**
             * @description Lateness is counted beyond this
             * @example 10
             */
            graceMinutes: number;
            /** @description Applies to anyone with no assignment */
            isDefault?: boolean;
            /** @example Piket */
            name: string;
        };
        CredentialHolderDto: {
            displayName: string | null;
            /** Format: uuid */
            id: string;
            /** @example 2024001 */
            identifier: string;
            photoUrl: string | null;
        };
        CredentialResponseDto: {
            holder: components["schemas"]["CredentialHolderDto"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            issuedAt: string;
            /** Format: uuid */
            replacedById?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            revokedReason?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "REVOKED" | "REPLACED";
            /** @enum {string} */
            subjectType: "STUDENT" | "EMPLOYEE";
            /** Format: uuid */
            userId: string;
        };
        CredentialWithCodeResponseDto: {
            /** @description Printed as the QR. Shown once at issue, then only for printing. */
            code: string;
            holder: components["schemas"]["CredentialHolderDto"];
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            issuedAt: string;
            /** Format: uuid */
            replacedById?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            revokedReason?: string | null;
            /** @enum {string} */
            status: "ACTIVE" | "REVOKED" | "REPLACED";
            /** @enum {string} */
            subjectType: "STUDENT" | "EMPLOYEE";
            /** Format: uuid */
            userId: string;
        };
        DecideLeaveRequestDto: {
            /**
             * @description Required on rejection — the requester is told why (FR-031).
             * @example Clashes with the exam timetable
             */
            reason: string;
        };
        DeviceResponseDto: {
            /** Format: uuid */
            id: string;
            isActive: boolean;
            /**
             * Format: date-time
             * @description How a silent gate becomes visible rather than inferred
             */
            lastSeenAt?: string | null;
            location?: string | null;
            name: string;
            /** Format: date-time */
            tokenIssuedAt: string;
        };
        DeviceWithTokenResponseDto: {
            device: components["schemas"]["DeviceResponseDto"];
            /** @description Shown once. Only its hash is stored. */
            token: string;
        };
        GateSuggestionDto: {
            checkInAt: Record<string, never> | null;
            lateMinutes: number;
            status: string;
            userId: string;
        };
        GateSuggestionListResponseDto: {
            data: components["schemas"]["GateSuggestionDto"][];
        };
        GateSuggestionQueryDto: {
            /** Format: date-time */
            date: string;
            userIds: string[];
        };
        IssueCredentialDto: {
            /** @enum {string} */
            subjectType: "STUDENT" | "EMPLOYEE";
            /**
             * Format: uuid
             * @description The person the card belongs to
             */
            userId: string;
        };
        LeaveTypeResponseDto: {
            /**
             * @description Null when the leave is not capped, or does not consume quota.
             * @example 12
             */
            annualQuota: number | null;
            /**
             * @description Whether this leave is for staff, students, or both.
             * @enum {string}
             */
            appliesTo: "STUDENT" | "EMPLOYEE";
            /** @example SAKIT */
            code: string;
            /** @example true */
            consumesQuota: boolean;
            /** Format: date-time */
            deletedAt: string | null;
            /** Format: uuid */
            id: string;
            /**
             * @description Retired kinds stay on record so past requests keep their meaning; the list hides them unless asked for.
             * @example true
             */
            isActive: boolean;
            /** @example Sakit */
            name: string;
            /** @example true */
            requiresDocument: boolean;
            /**
             * @description How a day under this leave is counted.
             * @enum {string}
             */
            treatment: "ON_LEAVE" | "OFFICIAL_DUTY";
        };
        MonthlyPresenceSummaryDto: {
            absentDays: number;
            earlyLeaveCount: number;
            lateCount: number;
            lateMinutes: number;
            leaveDays: number;
            officialDutyDays: number;
            presentDays: number;
            userId: string;
        };
        MonthlyPresenceSummaryListResponseDto: {
            data: components["schemas"]["MonthlyPresenceSummaryDto"][];
        };
        MonthlySummaryQueryDto: {
            month: number;
            userIds: string[];
            year: number;
        };
        NonWorkingDayDto: {
            /** @example 2026-08-17 */
            date: string;
            /** @example HUT RI */
            name: string;
            /**
             * Format: uuid
             * @description Provenance only — not a foreign key.
             */
            sourceCalendarId?: string;
        };
        RecordScanBatchDto: {
            /** @description An offline flush */
            scans: components["schemas"]["RecordScanDto"][];
        };
        RecordScanDto: {
            /**
             * Format: uuid
             * @description Device-generated. Reused on retry, which is what makes a flush idempotent.
             */
            clientEventId: string;
            /**
             * Format: uuid
             * @description Which anchor produced occurredAt
             */
            clockAnchorId?: string;
            /** @description The opaque token read from the card */
            code: string;
            /** @description Server-anchored derivation, sent only for scans taken offline. Absent means "stamp it now". */
            occurredAt?: string;
        };
        RecordStudentAbsenceDto: {
            /** Format: uuid */
            documentFileId?: string;
            /**
             * @description Defaults to the start date for a single day.
             * @example 2026-09-02
             */
            endDate?: string;
            /** Format: uuid */
            leaveTypeId: string;
            /** @example Sick note from the parents */
            reason: string;
            /** @example 2026-09-01 */
            startDate: string;
            /**
             * Format: uuid
             * @description The student, by user id
             */
            studentUserId: string;
        };
        RegisterDeviceDto: {
            /** @example Depan, dekat pos satpam */
            location?: string;
            /** @example Gerbang Utama */
            name: string;
        };
        ReplaceWorkPatternDaysDto: {
            /** @description All seven weekdays — a partial update is refused. */
            days: components["schemas"]["WorkPatternDayDto"][];
        };
        RevokeCredentialDto: {
            /** @example Kartu hilang */
            reason: string;
        };
        SubmitLeaveRequestDto: {
            /**
             * Format: uuid
             * @description Surat pendukung
             */
            documentFileId?: string;
            /** @example 2026-09-02 */
            endDate: string;
            /** Format: uuid */
            leaveTypeId: string;
            /** @example Keperluan keluarga */
            reason: string;
            /** @example 2026-09-01 */
            startDate: string;
        };
        UpdateDailyPresenceDto: {
            checkInAt?: string | null;
            checkOutAt?: string | null;
            note?: string | null;
            /** @example Lupa tap kartu, hadir sesuai jadwal piket */
            reason: string;
            /** @enum {string} */
            status?: "PRESENT" | "LATE" | "ABSENT" | "ON_LEAVE" | "OFFICIAL_DUTY" | "NOT_EXPECTED";
        };
        UpdateDeviceDto: {
            /** @description Deactivating refuses the token immediately */
            isActive?: boolean;
            location?: string;
            name?: string;
        };
        UpdateLeaveTypeDto: {
            /** @example 12 */
            annualQuota?: number;
            /** @enum {string} */
            appliesTo?: "STUDENT" | "EMPLOYEE";
            /** @example CUTI_MELAHIRKAN */
            code?: string;
            consumesQuota?: boolean;
            /** @description Deactivating stops new requests */
            isActive?: boolean;
            /** @example Cuti Melahirkan */
            name?: string;
            requiresDocument?: boolean;
            /**
             * @description OFFICIAL_DUTY means working elsewhere — it must not read as leave in a recap.
             * @enum {string}
             */
            treatment?: "ON_LEAVE" | "OFFICIAL_DUTY";
        };
        UpdateNonWorkingDayDto: {
            /** @example Libur Semester */
            name: string;
        };
        UpdateWorkPatternDto: {
            /**
             * @description Lateness is counted beyond this
             * @example 10
             */
            graceMinutes?: number;
            /** @description Applies to anyone with no assignment */
            isDefault?: boolean;
            /** @example Piket */
            name?: string;
        };
        WorkPatternDayDto: {
            /** @example 14:00 */
            endTime: string;
            isWorkingDay: boolean;
            /** @example 07:00 */
            startTime: string;
            /**
             * @description 0 = Sunday … 6 = Saturday
             * @example 1
             */
            weekday: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DailyRecordInternalController_byUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateSuggestionQueryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["GateSuggestionListResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DailyRecordInternalController_monthlySummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlySummaryQueryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["MonthlyPresenceSummaryListResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            details?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            };
                            /** @example {} */
                            error?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example {
                             *       "database": {
                             *         "status": "up",
                             *         "responseTime": 12
                             *       }
                             *     }
                             */
                            info?: {
                                [key: string]: {
                                    /** @description Time the health indicator took to respond, in ms */
                                    responseTime?: number;
                                    /** @enum {string} */
                                    status: "up" | "degraded" | "down";
                                } & {
                                    [key: string]: unknown;
                                };
                            } | null;
                            /**
                             * @example ok
                             * @enum {string}
                             */
                            status?: "ok" | "degraded";
                        };
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                    };
                };
            };
        };
    };
    CredentialController_list: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                /** @description Matches the holder name */
                search?: string;
                status?: "ACTIVE" | "REVOKED" | "REPLACED";
                subjectType?: "STUDENT" | "EMPLOYEE";
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CredentialResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CredentialController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueCredentialDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CredentialWithCodeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CredentialController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CredentialResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CredentialController_replaceCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeCredentialDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CredentialWithCodeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CredentialController_revokeCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeCredentialDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CredentialResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    CredentialController_print: {
        parameters: {
            query: {
                /** @description Comma-separated on the query string */
                userIds: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CredentialWithCodeResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DailyRecordController_list: {
        parameters: {
            query: {
                date: string;
                limit?: number;
                page?: number;
                status?: "PRESENT" | "LATE" | "ABSENT" | "ON_LEAVE" | "OFFICIAL_DUTY" | "NOT_EXPECTED";
                subjectType?: "STUDENT" | "EMPLOYEE";
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DailyRecordController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDailyPresenceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DailyRecordController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DailyRecordController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDailyPresenceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DailyRecordController_mine: {
        parameters: {
            query?: {
                month?: number;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DailyRecordController_recap: {
        parameters: {
            query: {
                month: number;
                subjectType?: "STUDENT" | "EMPLOYEE";
                userId?: string;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DailyRecordController_export: {
        parameters: {
            query: {
                month: number;
                subjectType?: "STUDENT" | "EMPLOYEE";
                userId?: string;
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DeviceController_list: {
        parameters: {
            query?: {
                isActive?: boolean;
                limit?: number;
                page?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["DeviceResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DeviceController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["DeviceWithTokenResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DeviceController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["DeviceResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DeviceController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["DeviceResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    DeviceController_rotate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["DeviceWithTokenResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_balancesFor: {
        parameters: {
            query?: {
                year?: string;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_myBalances: {
        parameters: {
            query?: {
                year?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_listRequests: {
        parameters: {
            query?: {
                requesterId?: string;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "WITHDRAWN";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitLeaveRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideLeaveRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_myRequests: {
        parameters: {
            query?: {
                requesterId?: string;
                status?: "PENDING" | "APPROVED" | "REJECTED" | "WITHDRAWN";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveTypeController_list: {
        parameters: {
            query?: {
                includeInactive?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeaveTypeResponseDto"][];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveTypeController_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLeaveTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeaveTypeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveTypeController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeaveTypeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveTypeController_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLeaveTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LeaveTypeResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_listHolidays: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_removeHoliday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkPatternController_renameHoliday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNonWorkingDayDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_bulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkNonWorkingDaysDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttendancePeriodController_list: {
        parameters: {
            query?: {
                year?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AttendancePeriodController_close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: number;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    AttendancePeriodInternalController_isClosed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month: number;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AttendancePeriodClosedResponseDto"];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
            /** @description Missing or invalid provisioning token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScanController_list: {
        parameters: {
            query?: {
                credentialId?: string;
                dateFrom?: string;
                dateTo?: string;
                deviceId?: string;
                limit?: number;
                outcome?: "ACCEPTED" | "DUPLICATE" | "REJECTED_UNKNOWN" | "REJECTED_REVOKED" | "REJECTED_INACTIVE" | "REJECTED_STALE";
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ScanController_scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordScanDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ScanController_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordScanBatchDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    ScanController_clock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    LeaveController_recordStudentAbsence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordStudentAbsenceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_listAssignments: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_assign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignWorkPatternDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_listPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkPatternDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkPatternDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
    WorkPatternController_putDays: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceWorkPatternDaysDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>[];
                        /** @example Success */
                        message?: string;
                        /** @example 200 */
                        statusCode?: number;
                    };
                };
            };
        };
    };
}
